### ISSUE TITLE
Timeout with MPIManager on OS X with Open-MPI

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/MPI.jl#113]
All the MPI tests except the `MPIManager` test works on my MacBook running El Capitan. For some reason there is a timeout when trying to connect MPI workers.

cc: @amitmurthy 

```jl
julia> using MPI
INFO: Recompiling stale cache file /Users/andreasnoack/.julia/lib/v0.4/MPI.ji for module MPI.

julia> man = MPIManager(np = 4)
MPI.MPIManager(np=4,launched=false,mode=MPI_ON_WORKERS)

julia> addprocs(man)
Error in MPI launch ErrorException("Timeout -- the workers did not connect to the manager")
ERROR (unhandled task failure): Timeout -- the workers did not connect to the manager
ERROR: Timeout -- the workers did not connect to the manager
 in wait at ./task.jl:111
 in addprocs_locked at multi.jl:1148
 in addprocs at multi.jl:1100

julia> versioninfo()
Julia Version 0.4.3-pre+6
Commit adffe19* (2015-12-11 00:38 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by eschnett** [comment]
Which version of `MPI.jl` is this?

**Comment by eschnett** [comment]
... and what MPI implementation is this?

**Comment by andreasnoack** [comment]
Open-MPI version 1.10.1 from Homebrew. I've tried both master and a version of `MPI.jl` and a version from September. The September version gives the error
```jl
Error in MPI launch AssertionError("length(manager.stdout_ios) == manager.np")
ERROR (unhandled task failure): AssertionError: length(manager.stdout_ios) == manager.np
ERROR: AssertionError: length(manager.stdout_ios) == manager.np
 in wait at ./task.jl:111
 in addprocs_locked at multi.jl:1148
 in addprocs at multi.jl:1100
```
so it might be something with OS X or Homebrew that has changed.

**Comment by eschnett** [comment]
I just tested this; this works fine for me (Julia 0.4 release branch, MPI master branch, El Capitan, OpenMPI 1.10.1 installed via MacPorts).

The MPI manager starts the MPI workers by calling `mpirun`. To debug this, you can add `info` (or `echo`) statements in that code, maybe redirecting output to a file. You could also output the result of `mpirun --version` or `which mpirun` to see whether MPI is installed correctly, and whether Julia detected it correctly.

**Comment by andreasnoack** [comment]
The other MPI tests work so I think MPI works. The output you asked is below
```
➜  MPI git:(master) ✗ which mpirun
/Users/andreasnoack/bin/mpirun
➜  MPI git:(master) ✗ mpirun --version
mpirun (Open MPI) 1.10.1

Report bugs to http://www.open-mpi.org/community/help/
```
I've also added an `@show` statement before the call to `mpirun` and at `mgr.stdout_ios` and `mgr.np` to show their values before the exception is thrown.
```jl
julia> addprocs(man)
expand(@cmd("\$(mgr.mpirun_cmd) \$(params[:exename]) -e \$setup_cmds")) = `mpirun -n 4 /Users/andreas
noack/julia/usr/bin/julia -e 'using MPI; MPI.setup_worker(167772165, 11000)'`
mgr.stdout_ios = IO[]
mgr.np = 4
Error in MPI launch ErrorException("Timeout -- the workers did not connect to the manager")
ERROR (unhandled task failure): Timeout -- the workers did not connect to the manager
 in launch at /Users/andreasnoack/.julia/v0.4/MPI/src/cman.jl:149
 in anonymous at task.jl:63
ERROR: Timeout -- the workers did not connect to the manager
 in wait at ./task.jl:111
 in addprocs_locked at multi.jl:1148
 in addprocs at multi.jl:1100
```
I can see from the Activity Monitor that four new julia processes are launched and `orterun` keeps spinning with 100pct. CPU even after I exit Julia.

**Comment by eschnett** [comment]
To debug this further, you could add more `info` / `@show` statements in the startup code, trying to determine where the new processes get stuck. It might be that the four newly processes don't find each other, or that the root process doesn't connect back to the Julia process that started them.

**Comment by andreasnoack** [comment]
Hm. Just tried this again and now it works. No idea why.
