### ISSUE TITLE
Tag MPI v0.4

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#114]
I'd like to tag MPI 0.4. We have a rewritten cluster manager, an updated install procedure, and new MPI functions wrapped.

**Comment by lcw** [comment]
Sounds good to me.

**Comment by eschnett** [comment]
Having said this, I see breakage with `@mpi_do` on Julia 0.5; the new way lambdas are implemented doesn't work with `Base.localize_vars`.

**Comment by andreasnoack** [comment]
...so maybe we should go ahead an tag.

**Comment by eschnett** [comment]
Yes we should.

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4800

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/commit/3fe79dd02c8688a86517ec4efcd2f5e119fef809
