### ISSUE TITLE
Appveyor tests are failing for Julia 0.5

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#123]
See https://ci.appveyor.com/project/eschnett/mpi-jl/branch/master.

**Comment by davidanthoff** [comment]
They pass locally on exactly the same julia 0.5 build on a x64 system... The error seems to occur when the MPIManager tries to use TCP to communicate with the clients, in that case the clients apparently don't manage to connect back to the host process (if I understand the architecture of all of this correctly). The odd thing is that things seem to work on julia 0.4 on appveyor, and on julia 0.5 on my system... I'm a little lost what the problem might be...

**Comment by davidanthoff** [comment]
Given that this works on julia 0.4, but not on julia 0.5, it would probably help if someone from julia core looked at this? @ViralBShah do you have an idea what might be causing this?

**Comment by andreasnoack** [comment]
I'm wondering if it was temporary. For some reason, I'm unable to restart the build but here it the 64 bit version pass and the 32 bit version just doesn't make it in time.

**Comment by davidanthoff** [comment]
Hm, the tests seem to fail consistently on julia 0.5, and it always just seems to be one specific test that fails, with later tests in the same build succeeding. Did you see a full test pass succeed on julia 0.5?

**Comment by andreasnoack** [comment]
Yes I'd actually planned to link to https://ci.appveyor.com/project/eschnett/mpi-jl/build/1.0.7/job/pd55krd2sp4oh4xy

**Comment by davidanthoff** [comment]
That build actually shows errors in the log, but then still indicates that it succeeded overall. Shouldn't this actually report as a failed build?

**Comment by andreasnoack** [comment]
I should have checked that before posting. It should have been a red light as well.

**Comment by davidanthoff** [comment]
#128 for that separate bug.

**Comment by davidanthoff** [comment]
Interestingly enough it seems that the 32 bit version on julia 0.5 now passes the tests, but the x64 doesn't. Strange...

**Comment by eschnett** [comment]
Since the Julia 0.5 Appveyor tests have been failing for some time, this makes the Appveyor test results rather useless. I'd rather have a green Appveyor by default, so that new Appveyor problems can be identified more readily. I am thus going to disable Appveyor with Julia 0.5. Let's use this issue to discuss how to result this.

**Comment by davidanthoff** [comment]
This really seems an issue that the julia core group needs to figure out, seems a pretty clear case of something working on julia 0.4 but not on 0.5... Not sure whom to ping, @ViralBShah?

**Comment by eschnett** [comment]
The error message in Appveyor is
```
Error in MPI launch ErrorException("Timeout -- the workers did not connect to the manager") 
ERROR: LoadError: Timeout -- the workers did not connect to the manager
 in wait(::Task) at .\task.jl:105
 in #addprocs_locked#328(::Array{Any,1}, ::Function, ::MPI.MPIManager) at .\multi.jl:1334
 in #addprocs#327(::Array{Any,1}, ::Function, ::MPI.MPIManager) at .\multi.jl:1287
 in addprocs(::MPI.MPIManager) at .\multi.jl:1285
 in include_from_node1(::String) at .\loading.jl:426
 in process_options(::Base.JLOptions) at .\client.jl:266
 in _start() at .\client.jl:322
while loading C:\Users\appveyor\.julia\v0.5\MPI\test\test_cman_julia.jl, in expression starting on line 7
ERROR (unhandled task failure): Timeout -- the workers did not connect to the manager
	Error: C:\Users\appveyor\.julia\v0.5\MPI\test\test_cman_julia.jl
```

This is caused by these lines:
```Julia
using Base.Test
using MPI

# Start workers via `mpiexec` that communicate among themselves via MPI;
# communicate with the workers via TCP
mgr = MPI.MPIManager(np=4)
addprocs(mgr)
```

So I think this has to do with `MPIManager`, Windows, and Julia 0.5. I think the cluster manager changed in Julia 0.5 -- maybe we're using the interface wrong, triggering a problem on Windows?

**Comment by simonbyrne** [comment]
All Appveyor tests are now passing (#276). Please open a new issue if further problems arise.
