### ISSUE TITLE
Wrong Fortran compiler picked up

### ISSUE THREAD

**Issue by dpo** [JuliaParallel/MPI.jl#14]
I thought I would mention here that installation failed for me because I have the Intel Fortran compiler lying around and an expired license, and that is the Fortran compiler that CMake picked up. I resolved the issue by changing the `cmake` call in `build.jl` as follows:
````
cmake -DCMAKE_Fortran_COMPILER=/usr/local/bin/gfortran ...
````
on line 15. I'm not sure what a generic solution to this problem would be. An explicit dependency on `gfortran` perhaps? Don't know if that's possible.

**Comment by eschnett** [comment]
You can now set environment variables that set the corresponding options to `cmake`; see <https://github.com/JuliaParallel/MPI.jl/blob/master/README.md>.

**Comment by eschnett** [comment]
This is probably resolved.
