### ISSUE TITLE
ERROR: LoadError: InitError: could not load symbol "mpi_iprobe_":  

### ISSUE THREAD

**Issue by mbrookhart** [JuliaParallel/MPI.jl#172]
I've checked out the lastest master of MPI.jl and used the environmental variables in the readme to point to the install of mpich on my cluster.  The build process workes perfectly, but when I try Pkg.test("MPI"), I get:

ERROR: LoadError: InitError: could not load symbol "mpi_iprobe_":  

Any ideas?

**Comment by eschnett** [comment]
This could have two different causes: Either your MPI library implements an older version of the standard where "MPI_Iprobe" is not yet available (I don't recall in which version it was introduced), or there is a configuration problem where MPI.jl misdetects the Fortran compiler's name mangling. The latter can in particular be the case if the MPI library doesn't work with the Fortran compiler you're using.

Can you post more details, e.g. the contents of the auto-generated scripts?

**Comment by mbrookhart** [comment]
Ah, that was a simple error, Cmake found and used gfortran instead of mpifort. Quick switch on the FC environment variable and all tests pass! Thanks.
