### ISSUE TITLE
Gromacs-5.1.4 installation with CUDA-v8.0 errors while running cmake...

### ISSUE THREAD

**Issue by shrikantcombio** [JuliaParallel/MPI.jl#176]
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Error at cmake/gmxManageMPI.cmake:178 (message):
  MPI support requested, but no MPI compiler found.  Either set the
  C-compiler (CMAKE_C_COMPILER) to the MPI compiler (often called mpicc), or
  set the variables reported missing for MPI_C above.
Call Stack (most recent call first):
  CMakeLists.txt:410 (include)

-- Configuring incomplete, errors occurred!
See also "/home/anshu/gromacs-5.1.4/build/CMakeFiles/CMakeOutput.log".
See also "/home/anshu/gromacs-5.1.4/build/CMakeFiles/CMakeError.log".
[root@localhost build]# cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/gromacs-5.1.4 -DBUILD_SHARED_LIBS=OFF -DGMX_PREFER_STATIC_LIBS=ON -DGMX_DEFAULT_SUFFIX=OFF -DGMX_BINARY_SUFFIX=-5.1.4 -DGMX_LIBS_SUFFIX=-5.1.4 -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_BUILD_OWN_FFTW=ON
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Error at cmake/gmxManageMPI.cmake:178 (message):
  MPI support requested, but no MPI compiler found.  Either set the
  C-compiler (CMAKE_C_COMPILER) to the MPI compiler (often called mpicc), or
  set the variables reported missing for MPI_C above.
Call Stack (most recent call first):
  CMakeLists.txt:410 (include)

-- Configuring incomplete, errors occurred!
See also "/home/anshu/gromacs-5.1.4/build/CMakeFiles/CMakeOutput.log".
See also "/home/anshu/gromacs-5.1.4/build/CMakeFiles/CMakeError.log".

**Comment by vchuravy** [comment]
This issue tracker is for the MPI interface in Julia. How does your problem relate to this package?

**Comment by andreasnoack** [comment]
Do you have MPI installed? If so, did you try
```
MPI support requested, but no MPI compiler found. Either set the
C-compiler (CMAKE_C_COMPILER) to the MPI compiler (often called mpicc), or
set the variables reported missing for MPI_C above.
```
from the error message you posted?

**Comment by simonbyrne** [comment]
CMake is no longer required (#271), so I'm assuming this is no longer an issue.
