### ISSUE TITLE
MPI advanced communicators

### ISSUE THREAD

**Issue by pancetta** [JuliaParallel/MPI.jl#178]
Are you planning to wrap advanced communicator functionality like MPI_COMM_SPLIT or MPI_CART_CREATE? Is this a matter of manpower or a technical thing?

**Comment by jpsamaroo** [comment]
I would love to have these features as well! I'm working on a small branch for adding MPI_COMM_SPLIT (but would be happy to include MPI_CART_CREATE and a few other useful methods), but I did notice that a previous PR #35 was closed after attempting to do something similar. The `COMM_SPLIT` identifier seems to already exist in a few places in the code, there just isn't a method available that uses it, so I figure just adding one function and two lines to `test_comm.jl` would be acceptable?

**Comment by simonbyrne** [comment]
Both of these functions are now available.
