### ISSUE TITLE
Running MPI in jupyter notebook

### ISSUE THREAD

**Issue by bhk37** [JuliaParallel/MPI.jl#180]
Is it possible to initialize multiple processes within a jupyter notebook? That is, something analogous to Ipython's MPI implementation: https://ipython.org/ipython-doc/3/parallel/parallel_mpi.html?

**Comment by andreasnoack** [comment]
You can `addprocs` with the `MPIManager` inside a notebook in the same way you can do it in e.g. the REPL. The issue tracker is mainly for bugs so please ask questions on discourse.julialang.org.
