### ISSUE TITLE
How to link or set  the MPI.jl environment and how to know which compiler is using?

### ISSUE THREAD

**Issue by mmonterrubio** [JuliaParallel/MPI.jl#197]
Hello,

I'm new in MPI for Julia and I want to use it for my model. My problem is related with the linking between the package folder .julia/v6.0/MPI with the MPI. It seems that  Julia lost the link and I don't know how to link it manually.
When I try to From Julia prompt the message is

julia> include("01-hello.jl")
[linux-5hui:02260] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_btl_usnic: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)                    
[linux-5hui:02260] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_ofi: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)                      
[linux-5hui:02260] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)                      
Hello world, I am 0 of 1    

And If I try to execute from the terminal the same example the message is

[mmonterr@linux-5hui ~/.julia/v0.6/MPI/examples]$ mpirun -np 4 julia 01-hello.jl                                  
ERROR: LoadError: ArgumentError: module MPI not found in current path.                                            
Run `Pkg.add("MPI")` to install the MPI package.
while loading /home/mmonterr/.julia/v0.6/MPI/examples/01-hello.jl, in expression starting on line 1
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[55478,1],0]
  Exit code:    1

Also I have tried to certain environment variables creating .juliarc script as in the documentation describes but also without success. Thank you.
Marisol

**Comment by andreasnoack** [comment]
Please use discourse.julialang.org for questions.
