### ISSUE TITLE
MPIManager functionality in Julia v0.6 and beyond

### ISSUE THREAD

**Issue by juliohm** [JuliaParallel/MPI.jl#207]
The README mentions that the MPIManager functionality together with the Julia parallel constructs (e.g. `pmap`) only work in Julia v0.4. Is there a major limitation that inhibits the package to be updated to Julia v0.6 and beyond?

**Comment by barche** [comment]
It actually does work on 0.6, there is also an alternative implementation using one sided communication here: https://github.com/JuliaParallel/MPI.jl/pull/203

**Comment by juliohm** [comment]
Thank you @barche, am I correct to say that the manager in the PR is windows-only? I am interested in the Linux case.

I will try the MPIManager locally to see how it works.

**Comment by barche** [comment]
No, the PR is actually linux/macos only, the window in the title is about MPI windows.
