### ISSUE TITLE
MPI.Gather with different sizes

### ISSUE THREAD

**Issue by milankl** [JuliaParallel/MPI.jl#218]
```julia
using MPI

MPI.Init()
comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)
size = MPI.Comm_size(comm)

a = rand(3+rank)
b = MPI.Gather(a,0,comm)

MPI.Finalize()

if rank == 0
    println(b)
end
```

This code executed with `mpirun -n 2` yields an error as the vectors `a` increase in size per rank (rank0 3-element Array, rank1 4-element Array, etc.). However, if I replace the line `a = rand(3+rank)` with `a = rand(3)` it works fine and the resulting vector `b` is a concatenation of all `a`'s. With `a = rand(3-rank)` the vector `b` actually contains empties and therefore I reckon the `MPI.Gather` function assumes a length of vector `b` to be `size*length(a)`, where `a` is the `a` of the receiving process. Is that behaviour desired? Or how am I supposed the concatenate vectors (or matrices) from different processors that in general could be of different size?

**Comment by simonbyrne** [comment]
Yes, `Gather` requires that all processes send the same amound

To send different numbers from each process you can use `Gatherv`:
```julia
using MPI

MPI.Init()
comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)
size = MPI.Comm_size(comm)

a = rand(3+rank)
b = MPI.Gatherv(a, Cint[3+rank for rank in 0:size-1], 0, comm)

MPI.Finalize()

if rank == 0
    println(b)
end
```
