### ISSUE TITLE
drop the dependency of cmake?

### ISSUE THREAD

**Issue by randy3k** [JuliaParallel/MPI.jl#22]
Currently, `MPI.jl` requires cmake to prepare the shared library. Shall we move to a more Julia way by using BinDeps? I believe most of the stuffes in cmake can be done by BinDeps.

**Comment by ViralBShah** [comment]
How about just depending on `mpif77` and `mpicc` to create libjuliampi? Those are standard.

**Comment by eschnett** [comment]
Creating a shared library is non-trivial. cmake can help us here. Another option would be to go with libtool for this. Or does BinDeps offer a mechanism?

Still, I'm not sure that BinDeps (or whatever else) know how to interact with `mpif77` to build a shared library. I know that `mpif77` can create object files and build executables, but shared libraries are another beast. Something needs to query `mpif77` to extract the necessary information, and needs to deal with creating a shared library while pulling other library dependencies in. The thing that is complicated with cmake -- finding the MPI libraries -- is something that is intrinsically complicated.

I would take a split approach, using separate solutions for "simple systems" (people's laptops and workstations) and "complex systems" (clusters etc., that may have special software installed, e.g. http://www.ncsa.illinois.edu/enabling/bluewaters). For a simple system, things need to work out of the box. For a complex system, people will know how to pass certain special options to `MPI.jl` to tell it the information it needs.

On simple systems, people will most likely have either OpenMPI or MPICH installed. We could special-case these two, i.e. detect them, and then know what to do, without cmake. And if neither is present, we could even download and install one of them (e.g. OpenMPI) -- this would allow people to play with `MPI.jl` even on their laptops, without having to install anything.

**Comment by ViralBShah** [comment]
It would be great to have an easy way to get the simple cases to start working first. Complex setups will anyways need to muck around with the configuration. We can even just pick, say, openmpi as the default supported MPI implementation for MPI.jl - that BinDeps installs. 

I spent the better part of half a day making this work on my mac today. I think BinDeps, and some default choices that give a working system quicker is certainly possible, and would attract others.

**Comment by lcw** [comment]
I like the idea of having a "simple systems" install that just works and a "complex systems" install that can be used on large scale cluster.

**Comment by schnaitterm** [comment]
`mpicc/f77/fort` and so on are just wrapper scripts that call the compiler with the right vars and libraries linked in. so instead of having to call `gfortran -L/path/to/mpi/lib -lmpi -lmpifort -I/path/to/mpi/include <other args>` you can just call `mpifort <other args>` if you want to know exactly what it's doing, just do a good old `vim $(which mpifort)` :)
