### ISSUE TITLE
Interest in JuliaCon 2019 MPI.jl Birds of Feather

### ISSUE THREAD

**Issue by lcw** [JuliaParallel/MPI.jl#235]
Is there any interest in holding a [Birds of Feather](https://pretalx.com/juliacon2019/cfp) for MPI.jl at 2019?  If so, would anybody like to submit one together with me?  I know the deadline is fast approaching.

I think it would be useful to discuss as a group how we should move this package forward.  Some things that come to mind:

  - make it easier to install / use;
  - allow mpi dependent binary packages to be distributed (e.g., Trilinos would not have to be built at `] add Trilinos` time.);
  - better coverage of the MPI standard including MPI version checking; and
  - develop an AbstractMPI (and associated SerialMPI) package so that we can write Julia code that will run without MPI installed.

cc: @simonbyrne

**Comment by jpsamaroo** [comment]
- A "nicer" user-facing API that abstracts away the MPI specific calls, where possible. Similar to the current CUDA GPU ecosystem.
- Interop with GPUifyLoops.jl
- CI tests running across real network fabric (I will happily volunteer my low-end IB hardware for this)

**Comment by barche** [comment]
I think it's a good idea, but I can't make it to JuliaCon this year unfortunately. I think all of your ideas are good, I'd add maybe switch to the C API and try to get the Windows version to also automatically generate the constants.

**Comment by lcw** [comment]
> I think it's a good idea, but I can't make it to JuliaCon this year unfortunately. I think all of your ideas are good, I'd add maybe switch to the C API and try to get the Windows version to also automatically generate the constants.

Bummer you can't make it; If we do it, it would be great to try to video conference you in.

**Comment by barche** [comment]
Yes, I would certainly not mind chiming in through a videoconference, if possible.

**Comment by lcw** [comment]
We ended up submitting a general Julia Parallel BoF.  Should be fun!
