### ISSUE TITLE
MPI.jl installed but won't run simple 01-hello.jl script

### ISSUE THREAD

**Issue by dsigler1234** [JuliaParallel/MPI.jl#237]
Hi I am trying to run the simple 01-hello.jl script from the MPI.jl repo with the following command:

mpirun -np 2 julia 01-hello.jl

When I do I get the following error:
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       dsigler-31368s
Executable: julia
--------------------------------------------------------------------------
2 total processes failed to start

Do you have anything thoughts on what is going wrong? Any help would be appreciated

Here is my Julia env

    Status `~/.julia/environments/v1.1/Project.toml`
  [8f4d0f93] Conda v1.2.0
  [31c24e10] Distributions v0.17.0
  [7073ff75] IJulia v1.16.0
  [b6b21f68] Ipopt v0.5.4
  [4076af6c] JuMP v0.19.0
  [da04e1cc] MPI v0.7.2
  [d3f7391f] Plasmo v0.2.0

**Comment by lcw** [comment]
From the error message it looks like `julia` is not in your path since `mpirun` can't find it.

**Comment by dsigler1234** [comment]
That was it. Thanks for your help!
