### ISSUE TITLE
Building error on cluster

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaParallel/MPI.jl#239]
Hi, I am trying to install MPI.jl on my university's cluster. The cluster has openmpi/3.1.2 and  Julia/1.0.3.

When I run `Pkg.add("MPI")`, the error is below:

┌ Error: Error building `MPI`:
│ [ Info: Attempting to create directory /home/tianjing/.julia/packages/MPI/b4xg           C/deps/build
│ [ Info: Changing directory to /home/tianjing/.julia/packages/MPI/b4xgC/deps/bu           ild
│ ERROR: LoadError: IOError: could not spawn `cmake -DCMAKE_INSTALL_PREFIX=/home           /tianjing/.julia/packages/MPI/b4xgC/deps/src -DCMAKE_LIB_INSTALL_PREFIX=/home/ti           anjing/.julia/packages/MPI/b4xgC/deps/usr/lib ..`: no such file or directory (EN           OENT)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{RawFD,RawFD,RawFD})            at ./process.jl:367
│  [2] (::getfield(Base, Symbol("##493#494")){Cmd})(::Tuple{RawFD,RawFD,RawFD})            at ./process.jl:509
│  [3] setup_stdio(::getfield(Base, Symbol("##493#494")){Cmd}, ::Tuple{RawFD,Raw           FD,RawFD}) at ./process.jl:490
│  [4] #_spawn#492(::Nothing, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at            ./process.jl:508
│  [5] _spawn at ./process.jl:504 [inlined]
│  [6] #run#503(::Bool, ::Function, ::Cmd) at ./process.jl:662
│  [7] run(::Cmd) at ./process.jl:661
│  [8] run(::BinDeps.SynchronousStepCollection) at /home/tianjing/.julia/package           s/BinDeps/ZEval/src/BinDeps.jl:521 (repeats 3 times)
│  [9] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/tianj           ing/.julia/packages/BinDeps/ZEval/src/dependencies.jl:944
│  [10] satisfy!(::BinDeps.LibraryDependency) at /home/tianjing/.julia/packages/           BinDeps/ZEval/src/dependencies.jl:922
│  [11] top-level scope at /home/tianjing/.julia/packages/BinDeps/ZEval/src/depe           ndencies.jl:977
│  [12] include at ./boot.jl:317 [inlined]
│  [13] include_relative(::Module, ::String) at ./loading.jl:1044
│  [14] include(::Module, ::String) at ./sysimg.jl:29
│  [15] include(::String) at ./client.jl:392
│  [16] top-level scope at none:0
│ in expression starting at /home/tianjing/.julia/packages/MPI/b4xgC/deps/build.           jl:54
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/std           lib/v1.0/Pkg/src/Operations.jl:1097

I finally installed MPI in head node, and `cmake --version` returned the version of cmake in head node.
But in worker node, `cmake --version` shows that there is no cmake.

**Comment by zhaotianjing** [comment]
It seems that I don't have cmake installed.
Could you please tell me how to check whether I have cmake and add cmake into path?

**Comment by lcw** [comment]
You need CMake on the node that is building MPI.jl.  Can you build MPI.jl on the head node?

**Comment by zhaotianjing** [comment]
I built CMake in head node, and use it in worker node. Does that okay? Will it affect something?
BTW could you please tell me how to combine MPI.jl with slurm? Before I use `mpicc` to compile the .c file and then use `srun` to run the compiled file.

**Comment by zhaotianjing** [comment]
BTW could you please provide more examples of MPI.jl? Or where I can find more examples?

**Comment by zhaotianjing** [comment]
Hi I have question on timing a MPI code, because I want to test the performance.
For example, if I split my code into 4 parallel jobs using MPI, then the `@time` will return 4 timing records.

The real time for these 4 jobs is the maximum or the sum?

eg.
```
  4.166182 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  3.853497 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  4.091061 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.169676 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.114676 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  0.705804 seconds (436.84 k allocations: 21.515 MiB, 0.50% gc time)
  4.054897 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  3.813533 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  4.148482 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.012410 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)

```

Thanks!

**Comment by jpsamaroo** [comment]
@zhaotianjing these last two comments should either be their own issues or, better yet, posts on Discourse, since your original issue appears to have been resolved.
