### ISSUE TITLE
What is the real @time for an MPI program?

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaParallel/MPI.jl#240]
Hi, I have a question on timing a MPI code, because I want to test the performance.
For example, if I split my code into 10 parallel jobs using MPI, then the `@time` will return 10 timing records. BTW, I also try to use `start = time(); ... ;elapsed = time() - start`, but it also return 10 records as `@time`.

Is the real time for these 10 jobs the maximum, or the sum?

eg.

  4.166182 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  3.853497 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  4.091061 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.169676 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.114676 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  0.705804 seconds (436.84 k allocations: 21.515 MiB, 0.50% gc time)
  4.054897 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  3.813533 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)
  4.148482 seconds (436.84 k allocations: 21.515 MiB, 0.08% gc time)
  4.012410 seconds (436.84 k allocations: 21.515 MiB, 0.09% gc time)

Thanks!

**Comment by vchuravy** [comment]
Please ask general questions like this on discourse.julialang.org

Since you are starting 10 jobs they all run in parallel, so the maximum is a reasonable measure
