### ISSUE TITLE
Windows MPI 10.0 now available

### ISSUE THREAD

**Issue by hearnsj** [JuliaParallel/MPI.jl#242]
MS-MPI version 10.0 dated October 2018 is now available. Perhaps this link should be in the README
https://www.microsoft.com/en-us/download/details.aspx?id=57467

I can test this version on Windows 10

**Comment by simonbyrne** [comment]
@hearnsj: thanks, I have added the changes to #241 and #243.

Do you know if it is necessary to add MPI to the PATH variable on Windows? I noticed it is in the Appveyor script, but not mentioned in the docs.

**Comment by simonbyrne** [comment]
Ah, I think the PATH is required just to find `mpiexec`.

This issue can be closed (fixed in #241 and #243).
