### ISSUE TITLE
32-bit Windows custom reduction operator failure

### ISSUE THREAD

**Issue by simonbyrne** [JuliaParallel/MPI.jl#246]
The 32-bit Windows tests are failing when calling `MPI.Reduce!` with user-defined reduction operation. I can't figure out the exact problem though.

If I simplify `test/test-reduce.jl` to:
```
using MPI

MPI.Init()

comm = MPI.COMM_WORLD
sz = MPI.Comm_size(comm)
rank = MPI.Comm_rank(comm)
root = sz-1

send_arr = Int[1,2,3]
recv_arr = zero(send_arr)

f(x,y) = x+y-1

MPI.Reduce!(send_arr, recv_arr, 3, f, root, comm)

MPI.Finalize()
```

Then I get:
```
$ mpiexec -n 2 julia --project test/test-reduce.jl

job aborted:
[ranks] message

[0] process exited without calling finalize

[1] terminated

---- error analysis -----

[0] on MSEDGEWIN10
julia ended prematurely and may have crashed. exit code 0xc0000005

---- error analysis -----
```

Output from running with `-debug` is [here](https://gist.github.com/simonbyrne/b6c509f1d1f70835ac183d69b78f98f6)

**Comment by simonbyrne** [comment]
Ah, I think it's because MSMPI uses the `stdcall` calling convention, and from the [Julia `@cfunction` docs](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/index.html#Creating-C-Compatible-Julia-Function-Pointers-1):

> Currently, only the platform-default C calling convention is supported. This means that @cfunction-generated pointers cannot be used in calls where WINAPI expects stdcall function on 32-bit windows, but can be used on WIN64 (where stdcall is unified with the C calling convention).

So basically, we can't have custom reduction operators on 32-bit windows.

**Comment by simonbyrne** [comment]
upstream issue: https://github.com/JuliaLang/julia/issues/5613

We should document this and remove the tests.

**Comment by barche** [comment]
Good job figuring this out! Is it worth keeping Win32 support at all for MPI.jl?

**Comment by simonbyrne** [comment]
I feel we should as long as it's not too much hassle. People occasionally add MPI as a dependency to other projects, and it helps shake out occasional faulty assumptions on other code.

**Comment by barche** [comment]
Ok, fair point!

**Comment by simonbyrne** [comment]
I have disabled these in #276.
