### ISSUE TITLE
Why Scatter fail in my code?

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaParallel/MPI.jl#257]
Hi, I tried to scatter an array with 8 elements into 4 parts, so the number of elements in each part is 2.
 
But I got the error "UndefVarError: ZFull not defined" when I run it with 4 jobs.

Could you please tell me why this code failed?

```
using MPI

function test()
    MPI.Init()

    comm = MPI.COMM_WORLD
    my_rank = MPI.Comm_rank(comm)
    cluster_size = MPI.Comm_size(comm)

    if my_rank==0
        ZFull = [1 ,2 ,3, 4, 5, 6, 7, 8]
    end

    Z = MPI.Scatter(ZFull,2,0,comm)

    MPI.Finalize()
end

test()
```

run by
```
 srun -N 1 -n 4 -t 1 julia test.jl
```

If I don't define `ZFull` inside root (rank=0), this code will work. But the problem is that each job will read `ZFull`, and will use a huge memory if `ZFull` is huge.

Thanks

**Comment by simonbyrne** [comment]
`ZFull` isn't defined on the other ranks. You should be able to use an empty array at the moment, i.e.
```julia
if my_rank==0
    ZFull = [1 ,2 ,3, 4, 5, 6, 7, 8]
else
    ZFull = Int[]
end
```

That said, this is poorly documented. Should we allow passing `nothing`?

**Comment by zhaotianjing** [comment]
Hi,

But my scatter is still unsuccessful, it seems I only have the scatter part on rank 0.

```
using MPI

function runc()
    MPI.Init()

    comm = MPI.COMM_WORLD
    my_rank = MPI.Comm_rank(comm)

    if my_rank==0
        ZFull = [1 2 3 4 5 6]
    else
        ZFull = Float64[]
    end

    local_Z = MPI.Scatter(ZFull,2,0,comm)
    
    println(my_rank,local_Z)

    MPI.Finalize()
end

runc()
```

When I have 3 tasks, this will return:
```
0[1, 2]
1[1.4822e-323, 1.97626e-323]
2[2.47033e-323, 2.96439e-323]
```

Could you please tell me how I can scatter successful?

**Comment by simonbyrne** [comment]
You are using arrays of different types: all calls to `MPI.Scatter` should use the same types, so either
```julia
    if my_rank==0
        ZFull = Float64[1 2 3 4 5 6]
    else
        ZFull = Float64[]
    end
```
or
```
    if my_rank==0
        ZFull = [1 2 3 4 5 6]
    else
        ZFull = Int[]
    end
```

**Comment by zhaotianjing** [comment]
Thanks,
I fixed that type error, and I still cannot scatter it into other tasks.
Then I change the name of the receive buff to the same name of the send buff, the scatter works.
For example, if I want to scatter an array called `ZFull`, then the scatted part should also named `ZFull`.

```
using MPI

function runc()
    MPI.Init()

    comm = MPI.COMM_WORLD
    my_rank = MPI.Comm_rank(comm)

    if my_rank==0
        ZFull = [1.0 2.0 3.0 4.0 5.0 6.0]
    else
        ZFull = Float64[]
    end

    ZFull = MPI.Scatter(ZFull,2,0,comm)
    
    println(my_rank,ZFull)

    MPI.Finalize()
end

runc()
```

```
0[1.0, 2.0]
1[3.0, 4.0]
2[5.0, 6.0]
```

Can I know why this works?

**Comment by simonbyrne** [comment]
It sounds like you want [`Scatter_in_place!`](https://juliaparallel.github.io/MPI.jl/latest/functions/#MPI.Scatter_in_place!)

**Comment by zhaotianjing** [comment]
Thank you.

Can I know how to scatter a matrix by row? 

Julia is column-major. It seems we can only scatter a matrix by column because `MPI.Scatter(array,count,0,comm)` will pick up the element column by column.

**Comment by simonbyrne** [comment]
I don't think it's currently possible in MPI.jl: based on [this question](https://stackoverflow.com/q/10788180/392585) we need to expose `MPI_Type_vector`.

**Comment by zhaotianjing** [comment]
Hi, when I scatter an array into different length of sub-array, there seems to have an error.
For example, here I scatter a 5-element array into two parts (2 elements + 3 elements).
```
using MPI

function runc()
    MPI.Init()

    comm = MPI.COMM_WORLD
    my_rank = MPI.Comm_rank(comm)

    if my_rank == 0
        batch_ele = 2
    else
        batch_ele = 3
    end

    if my_rank==0
        Z = [1,2,3,4,5]
    else
        Z = Int64[]
    end

    Z = MPI.Scatter(Z,batch_ele,0,comm) 

    @show Z

    MPI.Finalize()
end

runc()

```
I run above code using 2 tasks, and the result shows:
```
Z = [3, 4, 22577388529232]  #rank 1
Z = [1, 2]  #rank 0
```
Does that mean we can only scatter an array into sub-array with the same size?
What if I want to scatter a 5-element array with 2 tasks?

Thanks
