### ISSUE TITLE
CI failing for OpenMPI+MacOS on Travis

### ISSUE THREAD

**Issue by lcw** [JuliaParallel/MPI.jl#262]
We are getting random failures for the test suite for OpenMPI+MacOS on Travis, see for example [here](https://travis-ci.org/JuliaParallel/MPI.jl/jobs/540999657).

**Comment by simonbyrne** [comment]
Should we just allow failures for those?

**Comment by lcw** [comment]
Unless someone can reproduce the issue outside of Travis I am thinking yes.
