### ISSUE TITLE
Julia MPI test for MPI_Comm_spawn_multiple is missing the first 'count' argument and fails tests

### ISSUE THREAD

**Issue by markwdalton** [JuliaParallel/MPI.jl#269]
I confirmed standard MPICH implementation also has the same number of arguements:
MPI_Comm_spawn_multiple( count, (char **)array_of_commands, (char ***)array_of_argv, (int *)array_of_maxprocs, li, root, the_real_comm, &(ic.the_real_comm), array_of_errcodes ) ); 

https://www.mpich.org/static/docs/v3.1/www3/MPI_Comm_spawn_multiple.html
int MPI_Comm_spawn_multiple(int count, char *array_of_commands[],
                          char **array_of_argv[], const int array_of_maxprocs[],
                          const MPI_Info array_of_info[], int root, MPI_Comm comm,
                          MPI_Comm *intercomm, int array_of_errcodes[])

.julia/packages/MPI/U5ujD/test/test_spawn.jl 
failed process: Process(`aprun -b -N1 -n1 -n 1 /location/julia/1.0.3/bin/julia --code-coverage=none /install/.julia/packages/MPI/U5ujD/test/test_spawn.jl`, ProcessExited(134)) [134] 
* error: MPID_Comm_spawn_multiple(70): Function MPID_Comm_spawn_multiple not implemented 
** That error sometimes shows up when the wrong number of arguments are used 

Rank 0 [Thu Mar 14 17:52:07 2019] [c7-1c2s12n0] Fatal error in MPI_Comm_spawn: Other MPI error, error stack: 
MPI_Comm_spawn(144).........: MPI_Comm_spawn(cmd="/location/julia/1.0.3/bin/julia", argv=0x2aaaba12dd90, maxprocs=3, MPI_INFO_NULL, root=0, MPI_COMM_WORLD, intercomm=0x7fffffff4850, errors=0x2aaab9c5b8f0) failed 
MPID_Comm_spawn_multiple(70): Function MPID_Comm_spawn_multiple not implemented 

There is a valid MPI_Comm_spawn library call: 
* MPI_Comm_spawn(cmd="/location/julia/1.0.3/bin/julia", argv=0x2aaaba12dd90, maxprocs=3, MPI_INFO_NULL, root=0, MPI_COMM_WORLD, intercomm=0x7fffffff4850, errors=0x2aaab9c5b8f0) failed 
* int MPI_Comm_spawn(const char *command, char *argv[], int maxprocs, MPI_Info info, int root, MPI_Comm comm, MPI_Comm *intercomm, int array_of_errcodes[]) 

I found that 'man MPI_Comm_spawn_multiple' or the include file '/opt/cray/pe/mpt/7.7.3/gni/mpich-intel/16.0/include/mpicxx.h' have 9 arguments versus 8 in the other MPI_Comm_Spawn calls. 
* MPI_Comm_spawn_multiple( count, (char **)array_of_commands, (char ***)array_of_argv, (int *)array_of_maxprocs, li, root, the_real_comm, &(ic.the_real_comm), array_of_errcodes ) ); 

Julia code: 
ccall((:MPI_Comm_spawn, libmpi), Nothing, (Cstring, Ptr{Ptr{Cchar}}, Cint, CInfo, Cint, CComm, Ref{CComm}, Ptr{Cint}), 
command, argv, nprocs, CInfo(INFO_NULL), 0, CComm(comm), c_intercomm, errors)

**Comment by simonbyrne** [comment]
@markwdalton I don't quite understand is the problem: could you perhaps explain a little more? It is somewhat difficult to understand what you've pasted above (what is code, what is terminal output, etc.): it can be a bit easier if you make use of GitHubs markdown syntax (e.g. quote code and terminal output using triple backticks (```)).

As far as I know, we don't currently make use of `MPI_Comm_spawn_multiple` (there is a call to `MPI_Comm_spawn`). What version of Julia and MPI.jl are you using?

**Comment by markwdalton** [comment]
The user is running julia MPI.jl tests and is getting a error.   I fixed the mistakes and changing to aprun.    Perhaps he added the MPI_Comm_spawn_multiple, but it looks like the test cycles through the different tests and just assumes that MPI_Comm_spawn_multiple is the same as the other MPI_Comm_Spawn routines.  I also did not find the reference to use of the comm_spawn_multiple.

But here is the traceback he saw when running:
```
 [10] _start() at ./client.jl:425	Error: /userdir/.julia/packages/MPI/U5ujD/test/test_spawn.jl
failed process: Process(`aprun -b -N1 -n1 -n 1 /installdir/julia/1.0.3/bin/julia --code-coverage=none /userdir/.julia/packages/MPI/U5ujD/test/test_spawn.jl`, ProcessExited(134)) [134]
Stacktrace:
 [1] (::getfield(Main, Symbol("##5#9")){String,ErrorException})(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}) at /userdir/.julia/packages/MPI/U5ujD/test/_runtests.jl:71
 [2] #with_output_color#659(::Bool, ::Function, ::Function, ::Symbol, ::IOStream) at ./util.jl:366
 [3] with_output_color(::Function, ::Symbol, ::IOStream) at ./util.jl:364
 [4] runtests() at /userdir/.julia/packages/MPI/U5ujD/test/_runtests.jl:69
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1044
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:266
```

**Comment by simonbyrne** [comment]
what version of MPI.jl is this? You can find out by running `using Pkg; Pkg.status("MPI")`

**Comment by simonbyrne** [comment]
Also, I'm not familiar with Cray MPI: what is the difference between `aprun` and `mpirun`?

**Comment by markwdalton** [comment]
It is not a issue with aprun since aprun just sends the job out
effectively.  So for this
bug I would not focus on 'aprun'.   But aprun also handles a lot of control
of the process
placements, affinity, etc.

The issue is clearly with the test or the library.    The
MPI_Comm_spawn_multiple is
the only function that has the extra 'count' argument.

Do we want to look at getting your or someone from Julia/Julia-MPI access
to Crays?

Mark

**Comment by simonbyrne** [comment]
> The issue is clearly with the test or the library. The MPI_Comm_spawn_multiple is the only function that has the extra 'count' argument.

Yes, I agree. What version of MPI.jl are you using? The current version does not use `MPI_Comm_spawn_multiple`, so I'm trying to figure out if this can be fixed by simply updating the package.

> Do we want to look at getting your or someone from Julia/Julia-MPI access to Crays?

That could be useful.

**Comment by markwdalton** [comment]
The version that was previously run against was:
    Project.toml:version = "0.7.0"
And it looks like as of today he grabbed:
    Project.toml:version = "0.9.0"

I will see who would be the right person or I am okay with me being the sponsor also, but it may be nice for you to connect directly with Chapel or PE/MPI developers.   I will see what I can do.
And the Cray MPICH, the main reason is for the difference in networking (in this case the Aries network), perhaps it will be easier in the next machine type.

**Comment by simonbyrne** [comment]
@markwdalton Could you try out the changes on #271 on your system? If you clone the repository, check out the `sb/c-api` branch then do:
```
julia --project -e 'using Pkg; Pkg.build(); Pkg.test()'
```

**Comment by simonbyrne** [comment]
I've extensively changed the internals, so hopefully this should now be fixed. If not, please open a new issue.
