### ISSUE TITLE
Making Pkg.test() work

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPI.jl#27]
Pkg.test("MPI") currently does not work because there is no tests/runtests.jl.

Also, as @amitmurthy tells me, we will need the tests to not include MPI_Init and MPI_Finalize. How about also running all the tests through the MPIManager?

**Comment by jakebolewski** [comment]
A minimal version of this is working by running the tests in isolation.  I think that this will be easier to debug as the MPIManager, ClusterManager functionality is in a bit of flux.

We need more tests, but at least this will get CI support going.
