### ISSUE TITLE
Use the MPIEXEC found by FindMPI to lauch workers and also in test suite?

### ISSUE THREAD

**Issue by fverdugo** [JuliaParallel/MPI.jl#274]
It would be nice for users like me that workers are launched by default using the mpi installation found by CMAKE's FindMPI at the moment MPI.jl was build.

By looking at line 
https://github.com/JuliaParallel/MPI.jl/blob/7fcee0b9456eaf2efa6ef75bd17cec27cda085cb/src/cman.jl#L58
seems that the default value of `mpirun_cmd` uses the `mpiexec` binary found in the current `PATH`. However, this is not always what one wants if MPI.jl was configured with the variables `JULIA_MPI_<lang>_COMPILER` to point to a specific MPI installation.

Of course, one can workaround this by including the wanted MPI installation at the beginning of the PATH variable, but it would be nice that MPI.jl could remember for which MPI installation was built.

In the test suite, we have also a hardcoded `mpiexec` in the following lines, which leads to the same issue:

https://github.com/JuliaParallel/MPI.jl/blob/7fcee0b9456eaf2efa6ef75bd17cec27cda085cb/test/runtests.jl#L53

https://github.com/JuliaParallel/MPI.jl/blob/7fcee0b9456eaf2efa6ef75bd17cec27cda085cb/test/runtests.jl#L57

Hope this suggestion is useful!

**Comment by simonbyrne** [comment]
Yes, this is a good idea. We should definitely do this.

**Comment by fverdugo** [comment]
It shouldn’t be very difficult. A global const variable MPIEXEC in MPI.jl would be sufficient. I can patch it myself if you provide me some info on how to acces the build information and, from this, how to set the module variable.

**Comment by barche** [comment]
The easiest I can think of is to filter it out of the CMakeCache.txt file, adding this to the end of build.jl seems to work:

```julia
mpiexec_executable = ""
for line in eachline(joinpath(@__DIR__, "build", "CMakeCache.txt"))
    if startswith(line, "MPIEXEC_EXECUTABLE:")
        global mpiexec_executable = split(line, "=")[end]
    end
end
@show mpiexec_executable
@assert Sys.isexecutable(mpiexec_executable)
```

It might also be a good idea to allow this to be overridden using an environment variable.

**Comment by simonbyrne** [comment]
I was planning on tacking this after #271 was merged.
