### ISSUE TITLE
Travis CI: MPI installation failure on Linux

### ISSUE THREAD

**Issue by kose-y** [JuliaParallel/MPI.jl#290]
Installation of mpich and intel mpi fails on linux.

**Comment by kose-y** [comment]
Looks like this is happening somewhat randomly.

https://travis-ci.org/JuliaParallel/MPI.jl/builds/560302399?utm_source=github_status&utm_medium=notification

**Comment by simonbyrne** [comment]
This seems to have resolved itself recently.

**Comment by simonbyrne** [comment]
I spoke too soon:
```
[Traviss-Mac-80:86046] *** An error occurred in MPI_Barrier

[Traviss-Mac-80:86046] *** reported by process [2356281345,1]

[Traviss-Mac-80:86046] *** on communicator MPI_COMM_WORLD

[Traviss-Mac-80:86046] *** MPI_ERR_OTHER: known error not in list

[Traviss-Mac-80:86046] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,

[Traviss-Mac-80:86046] ***    and potentially your MPI job)
```

It may be worth trying out a different CI provider. I've had good luck with Azure Pipelines recently.
