### ISSUE TITLE
MPIManager should support MPICH

### ISSUE THREAD

**Issue by amitmurthy** [JuliaParallel/MPI.jl#30]
Currently the MPI cluster manager only works with openmpi. It needs to support mpich too. I can code this up, but I need to know which one is installed. Any pointers on how to detect the same?

**Comment by ViralBShah** [comment]
Perhaps look for particular symbols in the libmpi.so and similar files?

**Comment by lcw** [comment]
We might be able to find out at build time.  There is usually information in the mpi.h about which library is being used.  If we want to depend on MPI-3 (not sure if we do) we can use the function `MPI_GET_LIBRARY_VERSION `  see <http://blogs.cisco.com/performance/mpi-3-small-new-function-mpi_get_library_version/> for more info.
