### ISSUE TITLE
Build failing. Any suggestions? Thanks

### ISSUE THREAD

**Issue by gabrielgggg** [JuliaParallel/MPI.jl#300]
This is Julia version julia version 1.0.4 on Ubuntu 18.04.2 LTS. I use MPI with gfortran successfully on this system.

> ┌ Error: Error building `MPI`:
> │ -- The Fortran compiler identification is GNU 7.4.0
> │ -- The C compiler identification is GNU 7.4.0
> │ -- Check for working Fortran compiler: /usr/bin/f95
> │ -- Check for working Fortran compiler: /usr/bin/f95  -- works
> │ -- Detecting Fortran compiler ABI info
> │ -- Detecting Fortran compiler ABI info - done
> │ -- Checking whether /usr/bin/f95 supports Fortran 90
> │ -- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
> │ -- Check for working C compiler: /usr/bin/cc
> │ -- Check for working C compiler: /usr/bin/cc -- works
> │ -- Detecting C compiler ABI info
> │ -- Detecting C compiler ABI info - done
> │ -- Detecting C compile features
> │ -- Detecting C compile features - done
> │ -- Found Git: /usr/bin/git (found version "2.17.1")
> │ -- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
> │ -- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so (found version "3.1")
> │ -- Found MPI: TRUE (found version "3.1")
> │ -- Detecting Fortran/C Interface
> │ -- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
> │ -- Looking for MPI_Comm_c2f
> │ -- Looking for MPI_Comm_c2f - found
> │ -- Configuring done
> │ -- Generating done
> │ -- Build files have been written to: /home/username/.julia/packages/MPI/wu7um/deps/build
> │ Scanning dependencies of target gen_constants
> │ [ 14%] Building Fortran object CMakeFiles/gen_constants.dir/src/gen_constants.f90.o
> │ [ 28%] Linking Fortran executable gen_constants
> │ [ 28%] Built target gen_constants
> │ Scanning dependencies of target gen_functions
> │ [ 42%] Building C object CMakeFiles/gen_functions.dir/src/gen_functions.c.o
> │ /home/username/.julia/packages/MPI/wu7um/deps/src/gen_functions.c: In function ‘main’:
> │ /home/username/.julia/packages/MPI/wu7um/deps/src/gen_functions.c:103:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
> │    printf("const MPI_IN_PLACE = %d\n", ((int)MPI_IN_PLACE));
> │                                         ^
> │ [ 57%] Linking C executable gen_functions
> │ [ 57%] Built target gen_functions
> │ Scanning dependencies of target mpijl
> │ [ 71%] Generating compile-time.jl
> │ [ 71%] Built target mpijl
> │ Scanning dependencies of target juliampi
> │ [ 85%] Building Fortran object CMakeFiles/juliampi.dir/test_mpi.f90.o
> │ [100%] Linking Fortran shared library libjuliampi.so
> │ [100%] Built target juliampi
> │ [ 28%] Built target gen_constants
> │ [ 57%] Built target gen_functions
> │ [ 71%] Built target mpijl
> │ [100%] Built target juliampi
> │ Install the project...
> │ -- Install configuration: ""
> │ -- Installing: /home/username/.julia/packages/MPI/wu7um/deps/src/./compile-time.jl
> │ -- Installing: /home/username/.julia/packages/MPI/wu7um/deps/usr/lib/libjuliampi.so
> │ -- Set runtime path of "/home/username/.julia/packages/MPI/wu7um/deps/usr/lib/libjuliampi.so" to "/usr/lib/x86_64-linux-gnu/openmpi/lib"
> │ [ Info: Attempting to create directory /home/username/.julia/packages/MPI/wu7um/deps/build
> │ [ Info: Changing directory to /home/username/.julia/packages/MPI/wu7um/deps/build
> │ ERROR: LoadError: Provider BuildProcess failed to satisfy dependency juliampi
> │ Stacktrace:
> │  [1] error(::String) at ./error.jl:33
> │  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/username/.julia/packages/BinDeps/ZEval/src/dependencies.jl:945
> │  [3] satisfy!(::BinDeps.LibraryDependency) at /home/username/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
> │  [4] top-level scope at /home/username/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
> │  [5] include at ./boot.jl:317 [inlined]
> │  [6] include_relative(::Module, ::String) at ./loading.jl:1044
> │  [7] include(::Module, ::String) at ./sysimg.jl:29
> │  [8] include(::String) at ./client.jl:392
> │  [9] top-level scope at none:0
> │ in expression starting at /home/username/.julia/packages/MPI/wu7um/deps/build.jl:275
> └ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096

**Comment by gabrielgggg** [comment]
There is a libjuliampi.so file in wu7um/deps/build but also in wu7um/deps/usr/lib About 8k.
If I try "using MPI" I get

> ERROR: LoadError: LoadError: LoadError: error compiling #Info#1: could not load library "/home/username/.julia/packages/MPI/wu7um/deps/usr/lib/libjuliampi"
> /home/username/.julia/packages/MPI/wu7um/deps/usr/lib/libjuliampi.so: wrong ELF class: ELFCLASS64

**Comment by simonbyrne** [comment]
Can you try using the master branch (`]add MPI#master`)?

**Comment by gabrielgggg** [comment]
Hello! If I do that, it doesn't detect MPI:

> │ ERROR: LoadError: No MPI library found.
> │ Ensure an MPI implementation is loaded, or set the `JULIA_MPI_PATH` variable.
> │ Stacktrace:
> │  [1] error(::String) at ./error.jl:33
> │  [2] top-level scope at /home/username/.julia/packages/MPI/jimLh/deps/build.jl:42
> │  [3] include at ./boot.jl:317 [inlined]
> │  [4] include_relative(::Module, ::String) at ./loading.jl:1044
> │  [5] include(::Module, ::String) at ./sysimg.jl:29
> │  [6] include(::String) at ./client.jl:392
> │  [7] top-level scope at none:0
> │ in expression starting at /home/username/.julia/packages/MPI/jimLh/deps/build.jl:41
> └ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096

**Comment by gabrielgggg** [comment]
This julia installation is from the snap, if it makes a difference.

**Comment by simonbyrne** [comment]
I'm not familiar with snap, but I don't think it would make a difference.

The error suggests it can't find the MPI installation. What MPI library do you have installed, and how did you install it?

You can try setting some of the environment variables described here: https://juliaparallel.github.io/MPI.jl/latest/installing/

**Comment by gabrielgggg** [comment]
Could the problem be that we're still looking for 32 bit stuff?

> @ Pkg.Operations /buildworker/worker/**package_linux32**/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096

This is Ubuntu's OpenMPI package. I am using it myself with Fortran. I don't know which of these paths to use

> ompi_info --path all
>                   Prefix: /usr
>              Exec_prefix: /usr
>                   Bindir: /usr/bin
>                  Sbindir: /usr/sbin
>                   Libdir: /usr/lib/x86_64-linux-gnu/openmpi/lib
>                   Incdir: /usr/lib/x86_64-linux-gnu/openmpi/include
>                   Mandir: /usr/share/man
>                Pkglibdir: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi
>               Libexecdir: /usr/lib/x86_64-linux-gnu
>              Datarootdir: /usr/share
>                  Datadir: /usr/share
>               Sysconfdir: /etc/openmpi
>           Sharedstatedir: /usr/com
>            Localstatedir: /var
>                  Infodir: /usr/share/info
>               Pkgdatadir: /usr/share/openmpi
>                Pkglibdir: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi
>            Pkgincludedir: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi

**Comment by gabrielgggg** [comment]
It was the snap installation for julia... maybe?

Installation of MPI.jl works as intended on Julia 1.1.1 downloaded from website.
