### ISSUE TITLE
Error: MPI_ERR_OP: invalid reduce operation

### ISSUE THREAD

**Issue by ugirumurera** [JuliaParallel/MPI.jl#304]
I downloaded the MPI package. I got the 01-hello.jl example to work, but none of the other examples work. The reduce example gives error: the reduction operation MPI_SUM is not defined on the MPI_INTEGER8 datatype
I am using Julia 1.1. Is this a version issue? Any way to solve this?

Thanks.

Juliette

**Comment by simonbyrne** [comment]
What version of MPI.jl are you using?

**Comment by simonbyrne** [comment]
And what MPI implementation are you using?

**Comment by simonbyrne** [comment]
Given the lack of further information, I'm closing this for now.
