### ISSUE TITLE
Is that possible to send/receive a number instead of array?

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaParallel/MPI.jl#308]
Hi, I want to send a number between two rank via point-to-point communication.
But I found the send/receive function only allows the array to be sent.

Assume we have 2 ranks. The following code failed:
```
using MPI
MPI.Init()

comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)

if rank==0
    data=7.0
    MPI.Send(data,1,99,comm) 
elseif rank==1
    data=[]
    MPI.Recv!(data,0,99,comm)
    println(data)
end


MPI.Finalize()
```
Could you please tell me how to send a number?

Thanks,
Tianjing

**Comment by simonbyrne** [comment]
To follow up on this, you can also now do:
```julia
if rank == 0
    data = 7.0
    MPI.Send(data,1, 99,comm)
elseif rank == 1
    data = MPI.Recv(Float64,0,99, comm)
    println(data)
end
```
which should be more efficient as it won't incur serialization overhead.
