### ISSUE TITLE
Issues using MPI.jl in REPL

### ISSUE THREAD

**Issue by markowkes** [JuliaParallel/MPI.jl#309]
Is it possible to debug, even a serial, version of a code that contains MPI calls in the REPL?  The issue I'm seeing is that MPI.Init() fails if the code is executed more than once.  See the MWE below:
```
julia> using MPI

julia> MPI.Init()

julia> MPI.Finalize()

julia> MPI.Finalized()
true

julia> MPI.Init()
ERROR: MPI REFCOUNT in incorrect state
Stacktrace:
 [1] Init() at /Users/mowkes/.juliapro/JuliaPro_v1.2.0-1/packages/MPI/RzbIV/src/environment.jl:47
 [2] top-level scope at none:0
```

**Comment by simonbyrne** [comment]
MPI does not let you call `MPI_Init` multiple times. From the spec
> All MPI programs must contain exactly one call to an MPI initialization routine: MPI_INIT or MPI_INIT_THREAD. Subsequent calls to any initialization routines are erroneous.

We should probably throw a more informative error message though.
