### ISSUE TITLE
`MPI.Finalized` fails after `MPI.Cart_create`

### ISSUE THREAD

**Issue by gasagna** [JuliaParallel/MPI.jl#315]
Here is a MWE. 

I noticed the `MPI.Finalized()` call is commented out in many of the `test_cart_***.jl` tests.

```julia
using MPI
using Test

MPI.Init()

comm = MPI.COMM_WORLD
comm_size = MPI.Comm_size(comm)
# comment line below and everything is fine
comm_cart = MPI.Cart_create(comm, 1, Cint[comm_size], Cint[1], false)

MPI.Finalize()
@test MPI.Finalized()
```

Anyone knows a fix for this?

**Comment by simonbyrne** [comment]
I commented them out when I added the reference tracking. The issue is that there are still references to MPI objects, so MPI_Finalize still has not been invoked.

Would be good to fix though: the easiest option is to assign nothing to the variables and call gc()
