### ISSUE TITLE
Finalizer problem with MPIManager

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/MPI.jl#33]
Occasionally, when working with `MPIManager` and `DArray`s I get the error message
```julia
error in running finalizer: Base.AssertionError(msg="p.handle != C_NULL")
```
I'll try to construct a minimal example, but I haven't been able to do so yet.

**Comment by lcw** [comment]
Thanks for the report.  If you get a minimal example that will definitely help track it down.  I don't have much experience with the MPIManager. @amitmurthy would have a better idea what is going on.

**Comment by amitmurthy** [comment]
Do you get it when the program is terminating? Because the only finalizer installed is 

```
            io, proc = open(`tail -f $output_dir/$f`)
            finalizer(proc, (x)->kill(x))
```

which is used to ensure that the spawned `tail` commands are terminated, when the new MPI workers have been removed.

I could try removing the `tail -f` and replacing it with a file polling mechanism.

**Comment by andreasnoack** [comment]
Yes. It is when termination and I can trigger it by the lines below
```julia
julia> using MPI

julia> manager = MPIManager(np = 4)
MPI.MPIManager(4,`mpirun -np 4 --output-filename /tmp/user/1021/juliaJnSyAC`,"/tmp/user/1021/juliaJnSyAC",60,Dict{Int64,Int64}(),Dict{Int64,Int64}(),RemoteRef(1,1,3),false)

julia> addprocs(manager)
4-element Array{Any,1}:
 2
 3
 4
 5

julia> quit()
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
andreasnoackjensen@julia:~$ julia-dev
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3412 (2015-02-18 22:03 UTC)
 _/ |\__'_|_|_|\__'_|  |  anj/darray/cde1949* (fork: 1 commits, 1 day)
|__/                   |  x86_64-linux-gnu

julia> using MPI

julia> manager = MPIManager(np = 4)
MPI.MPIManager(4,`mpirun -np 4 --output-filename /tmp/user/1021/juliaPxJRMV`,"/tmp/user/1021/juliaPxJRMV",60,Dict{Int64,Int64}(),Dict{Int64,Int64}(),RemoteRef(1,1,3),false)

julia> addprocs(manager)
4-element Array{Any,1}:
 2
 3
 4
 5

julia> quit()
error in running finalizer: Base.AssertionError(msg="p.handle != C_NULL")
error in running finalizer: Base.AssertionError(msg="p.handle != C_NULL")
error in running finalizer: Base.AssertionError(msg="p.handle != C_NULL")
```
It appears to flip between the two error messages. Maybe related, while writing the ScaLAPACK wrappers, the MPI workers will sometimes crash because I write illegal code. This has left quite a few open tail processes. Maybe it is not possible to terminate them when the workers crash, but it would be useful if possible.

**Comment by amitmurthy** [comment]
I'll remove the `tail -f` entirely and replace it with a Julia file watching mechanism.

**Comment by ViralBShah** [comment]
That will have the benefit of working on Windows too - although nobody probably uses MPI on windows.
