### ISSUE TITLE
`Scatter` in place and Similar

### ISSUE THREAD

**Issue by PhilipVinc** [JuliaParallel/MPI.jl#333]
With #324 the utility in_place versions of `Scatter` and similar operations (`Gather`, `Reduce`) have been removed.
Back in #232 I had introduced them so that users who are not familiar with C MPI (or don't feel comfortable reading the C MPI reference) could use the inplace version of `Scatter`. 

Essentially `Scatter_in_place!(but, count, root, comm)` was equivalent to
```
  if root == MPI.Comm_rank(comm)
      Scatter!(buf, MPI.IN_PLACE, count, root, comm)
  else
      Scatter!(C_NULL, buf, count, root, comm)
  end
```
I had chosen the name `_in_place` to highlight the fact that this is not a standard MPI method.

Upon further thought, I think that it would be nice to reintroduce this method as `Scatter!` with one less argument, like
```
function Scatter!(buf, count root, comm)
  if root == MPI.Comm_rank(comm)
      Scatter!(buf, MPI.IN_PLACE, count, root, comm)
  else
      Scatter!(C_NULL, buf, count, root, comm)
  end
end
```

It would make code more readable, I believe. Do maintainers agree or you have something against this idea?

cc @simonbyrne

**Comment by simonbyrne** [comment]
I did think about that, but my main rationale for not doing so is that the `buf` argument itself is not consistent across ranks: on the root rank it is `Comm_size(comm)` times larger.

I'm actually in the process of revamping the collective operations to support more general datatypes by defining intermediate "Buffer" types (#335): it might be possible to do something like that by dispatching on the buffer types. This will require some more thought though.

**Comment by PhilipVinc** [comment]
Fair enough,
Though in the case of `Scatterv` all buffers have the same size

**Comment by simonbyrne** [comment]
> Though in the case of `Scatterv` all buffers have the same size

What do you mean?

**Comment by PhilipVinc** [comment]
Hmm.. no. Nevermind. 
I confused myself. 
Ignore my comment
