### ISSUE TITLE
Move functionality to submodules

### ISSUE THREAD

**Issue by simonbyrne** [JuliaParallel/MPI.jl#338]
Should we make submodules match MPI function groupings? I've done this for certain additions (`MPI.Types` for `MPI_Type_XXX` functions, `MPI.File` for `MPI_File_XXX` functions). Should we do this for others? e.g. `MPI_Comm_XXX`, `MPI_Cart_XXX`, `MPI_Win_XXX`.

This is slightly complicated by the fact that `Comm` and `Win` are already used by type names. So in that case we would either need to rename the types (e.g. to `Communicator` and `Window`), or use different names for the modules (one convention in Julia is to use the plural name for the module, e.g. `Comms`, so that the function would be `MPI.Comms.rank`).

Thoughts?

**Comment by lcw** [comment]
I am okay with making submodules match MPI function groupings.  The main thing I would like to see is that the interface is consistent.  So if we do it in one place we do it everywhere, if possible.

**Comment by simonbyrne** [comment]
I agree. I chose `MPI.Types` instead of `MPI.Type` to avoid conflicts with `Type{X}` (I thought it was a reserved word, but it isn't, so we could work around it by referring to `Base.Type{T}` where necessary).

**Comment by lcw** [comment]
At first glance `MPI.Comms.rank` feels weird but if we are consistent everywhere (i.e., use the plural name for every module) then the interface should be fairly discoverable.

**Comment by ViralBShah** [comment]
It really should be `MPI.Comm.rank`. Comms just sounds really wrong.

**Comment by PhilipVinc** [comment]
Since we're talking about changing the MPI naming convention, and Julia has dispatch: 
Why shouldn't `MPI.rank(::MPI.Comm.Communicator)` just work? Of course calling `MPI.rank` on an array makes no sense, so `MPI.Comm` is ultimately redundant...

**Comment by simonbyrne** [comment]
If we do name the module `Comm`, what do people prefer for the type name: `Communicator` (vote 🎉) or `CommHandle` (vote 🚀)?

**Comment by eschnett** [comment]
People will expect the type name to be one of `MPI_Comm`, `MPI.Comm`, `Comm`, etc. Changing this is very invasive.

Changing the function name is more easily possible. I think that object-oriented MPI bindings are not a good pattern to follow because Julia has multiple dispatch. In C++, one would write `comm.rank()` (where `comm` is an object of type `MPI::Comm`). The Julia equivalent is `rank(comm)`, or `MPI.rank(comm)` (depending on how the module is imported).

**Comment by ViralBShah** [comment]
I would also be ok with not doing submodules.

**Comment by lcw** [comment]
I am okay without submodules as well and like `MPI.rank(comm)`.

**Comment by simonbyrne** [comment]
I can live with that.
