### ISSUE TITLE
MPI_Gather

### ISSUE THREAD

**Issue by rajexplo** [JuliaParallel/MPI.jl#348]
Hello All -
I am trying to Gather a datatype struct from all the processes and here is the pice of code an it is throwing an error. 
```julia
#using MPI
using Test
import MPI

Base.@kwdef mutable struct Particle # Base.@kwdef lets you define default values for the fields in structs.
    x;
    v = zeros(length(x));
    x_best = copy(x);
    y_best =Inf;
end



MPI.Init()
comm=MPI.COMM_WORLD
size=MPI.Comm_size(comm)
rank=MPI.Comm_rank(comm)
x=[1, 2, 3,4]
buf1=Particle(x , x, copy(x), Inf)
buf2 = Array{Particle}(undef, size)
buf2=MPI.Gather(buf1, 0, comm)
MPI.Finalize()
```

The error is
```
ERROR: ERROR: LoadError: LoadError: ArgumentError: Type must be isbitstype()
Stacktrace:ArgumentError: Type must be isbitstype()
Stacktrace:
 [1] 
 [1] (::MPI.var"#10#11"{Particle})(::MPI.var"#10#11"{Particle})() at /home/rajshukla/.julia/packages/MPI/hcbnk/src/datatypes.jl:39
 [2] get! at ./dict.jl:452 [inlined]
 [3] mpitype at /home/rajshukla/.julia/packages/MPI/hcbnk/src/datatypes.jl:37 [inlined]
 [4] Gather!(() at /home/rajshukla/.julia/packages/MPI/hcbnk/src/datatypes.jl:39
 [2] get! at ./dict.jl:452 [inlined]
 [3] mpitype at /home/rajshukla/.julia/packages/MPI/hcbnk/src/datatypes.jl:37 [inlined]
 [4] Gather!(::::Array{Particle,1}, ::Array{Particle,1}, ::Int64, ::Int64, ::MPI.Comm) at /home/rajshukla/.julia/packages/MPI/hcbnk/src/collective.jl:422
 [5] Gather(::Array{Particle,1}, ::Int64, ::MPI.Comm) at /home/rajshukla/.julia/packages/MPI/hcbnk/src/collective.jl:445
 [6] Gather(::Particle, ::Int64, ::MPI.Comm) at /home/rajshukla/.julia/packages/MPI/hcbnk/src/collective.jl:451
 [7] top-level scope at /project2/rcc/raj/Booth/non_gaap/model/test.jl:21
 [8] include at ./boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1105
 [10] include(::Module, ::String) at ./Base.jl:31
 [11] exec_options(::Base.JLOptions) at ./client.jl:287
 [12] _start() at ./client.jl:460
```
I will appreciate for your help.

**Comment by ali-ramadhan** [comment]
As the error suggests, the problem is that the struct you created is not `isbitstype` and not C compatible.

The `isbitstype` docstring has a useful description:
```
help?> isbitstype

  isbitstype(T)

  Return true if type T is a "plain data" type, meaning it is immutable and contains
  no references to other values, only primitive types and other isbitstype types.
  Typical examples are numeric types such as UInt8, Float64, and Complex{Float64}.
  This category of types is significant since they are valid as type parameters, may
  not track isdefined / isassigned status, and have a defined layout that is
  compatible with C.
```

PS: You might want to consider concretely typing your `Particle` struct like so
```julia
Base.@kwdef mutable struct Particle{X, V, XB, YB}
         x :: X
         v :: V  = zeros(length(x))
    x_best :: XB = copy(x)
    y_best :: YB = Inf
end
```
to allow the compiler to infer types (and avoid type instabilities), and allow for multiple dispatch.

If you inspect a `Particle`
```julia
julia> p = Particle(x=0.1)
Particle{Float64,Array{Float64,1},Float64,Float64}(0.1, [0.0], 0.1, Inf)

julia> isbits(p)
false

julia> isbits(p.x)
true

julia> isbits(p.v)
false

julia> isbits(p.x_best)
true

julia> isbits(p.y_best)
true
```
you'll see that the array is not `isbits` which makes the entire `Particle` object not `isbits` as well.

I know you can use [`MPI.send`](https://juliaparallel.github.io/MPI.jl/latest/pointtopoint/#MPI.send) and [`MPI.recv`](https://juliaparallel.github.io/MPI.jl/latest/pointtopoint/#MPI.recv) to send and receive serialized objects (which is slow but they don't have to be `isbits`).

Unfortunately I'm actually not 100% sure how to use `MPI.Gather` with your `Particle` struct so I'm hoping someone else will chime in.

PS²: It would help if you enclosed your code blocks in triple quotes (```) so your code is more readable.

**Comment by rajexplo** [comment]
@ali-ramadhan Thank you very much Ali.

**Comment by simonbyrne** [comment]
If you can replace the `Array`s by an `isbitstype`, such as a `Tuple` or an `SArray` (from the StaticArrays.jl package) then it should just work. I would only do this if your array sizes are fixed and small though.

We should add a `gather` which can handle serialization.

**Comment by rajexplo** [comment]
@simonbyrne Thanks you! Could you please provide an example?

**Comment by simonbyrne** [comment]
@rajexplo hopefully this explains what I mean:

```julia
using MPI
using StaticArrays
using Test

struct Particle
    x::SVector{4,Float64}
    v::SVector{4,Float64}
    x_best::SVector{4,Float64}
    y_best::Float64
end

MPI.Init()
comm=MPI.COMM_WORLD
size=MPI.Comm_size(comm)
rank=MPI.Comm_rank(comm)
x= @SVector [1, 2, 3,4]
buf1 = [Particle(x , x, x, Inf)]
@test isbitstype(eltype(buf1))

buf2 = MPI.Gather(buf1, 0, comm)
if rank == 0
    @test length(buf2) == size
end
MPI.Finalize()
```

**Comment by krajshukla** [comment]
@simonbyrne Thank you very much.

**Comment by krajshukla** [comment]
@simonbyrne I had a question. will this work with mpi and julia
mpirun -np 2 --map-by node julia -p 28 test.jl

Will mpi process will create 28 julia works if mapped by node?

**Comment by simonbyrne** [comment]
That is probably not what you want: it will start 2 MPI ranks, each of which will start a julia session with 28 julia processes (the script will only run on the master Julia process in each rank, unless you use the [Distributed stdlb](https://docs.julialang.org/en/v1/stdlib/Distributed/index.html)).

In general, I wouldn't encourage mixing MPI and Julia's own Distributed functionality.

**Comment by rajexplo** [comment]
@simonbyrne Thanks!Yes I have used Distributed. Idea is to map rank on each individual nodes and cores on each node will julia workers.I was thinking of MPI+OPENMP functionality. Is there  any alternative for that..

**Comment by ali-ramadhan** [comment]
@rajexplo You might be interested in https://github.com/JuliaGPU/KernelAbstractions.jl for OpenMP + CUDA functionality. It's still under rapid early development and is an upgraded version of https://github.com/vchuravy/GPUifyLoops.jl.

**Comment by simonbyrne** [comment]
Ah, that makes sense, as then you can leverage `SharedArray`s etc. I think that should work as long as only the master process performs MPI operations.

I'd be keen to hear how you go: as far as I know no one has really tried this, so it would be good to document what works and what doesn't.

**Comment by rajexplo** [comment]
@simonbyrne You mean that approach I mentioned (mpirun -np 1 julia -p 28 ) not CUDA what @ali-ramadhan mentioned. Thanks! I will update this  thread. Thanks!

**Comment by simonbyrne** [comment]
Yes, exactly.

An alternative is to use Julia threads: we need to expose MPI_Init_threads though

**Comment by rajexplo** [comment]
Yes Similar to MPI+OpenMP for C and FORTRAN!

**Comment by rajexplo** [comment]
@simonbyrne Thanks Simon! I will update this thread as I get it done..
