### ISSUE TITLE
MPI.Type_Vector undefined

### ISSUE THREAD

**Issue by pnavaro** [JuliaParallel/MPI.jl#350]
I think there is an issue with MPI_Type_vector:
```julia
julia> Pkg.status()
    Status `~/JuliaProjects/maxwell_yee_2d_with_mpi/Project.toml`
  [da04e1cc] MPI v0.11.0
julia> MPI.Type_Contiguous
Type_Contiguous (generic function with 1 method)
julia> MPI.Type_Vector
ERROR: UndefVarError: Type_Vector not defined
```
The example in the source code doesn't work either.

The `MPI.Type_Contiguous` works but i think i am using it wrong. The way I pass the old datatype seems weird to me.
```julia
MPI_REAL8 = MPI.Datatype(MPI.MPI_Datatype(MPI.MPI_DOUBLE))
column_type = MPI.Type_Contiguous(mx+1, MPI_REAL8)
MPI.Type_Commit!(column_type)
```
Many thanks for this package, i was looking forward to MPI-2.

**Comment by simonbyrne** [comment]
Can you try the current `master`? I have significantly changed the interface in #329, see the latest docs: https://juliaparallel.github.io/MPI.jl/latest/advanced/#Datatype-objects-1

**Comment by simonbyrne** [comment]
Also, on the current master creating datatypes should be largely unnecessary, at least for basic send/recv: things should just work if you pass a view.

**Comment by pnavaro** [comment]
Thank you very much Simon, it works perfectly and it is fast \o/

My example is here :
https://github.com/pnavaro/maxwell_yee_2d_with_mpi
