### ISSUE TITLE
Enabling 2FA on the JuliaParallel org

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPI.jl#368]
I wasn't sure of the best place to bring this up. I think we should be enabling 2FA on this org for everyone. @lcw I think you are the only major contributor in here without 2FA. Would it be possible for you to set it up?

**Comment by lcw** [comment]
sure, done

**Comment by ViralBShah** [comment]
@kpamnany could you also set up 2fa?

**Comment by kpamnany** [comment]
Done.

**Comment by ViralBShah** [comment]
I have made it mandatory now. Some people would have lost access, but I am happy to reinstate people who'd like to. I'm reasonably sure many of them are not active - but I could have been wrong.
