### ISSUE TITLE
`corrupted double-linked list (not small)` error on Slurm cluster

### ISSUE THREAD

**Issue by marius311** [JuliaParallel/MPI.jl#369]
I'm trying to use MPI.jl on a Slurm cluster. A couple of things seem to go wrong. 

First, building MPI.jl by running `pkg> build MPI` hangs, and on the log I see a segfault. However, if I run `julia build.jl` straight from the `deps/` directory it builds fine. By inserting a print statement, I have verified that I have `MPI_LIBRARY_ABI = MPICHABI`. I also tried commenting out the `if MPI_LIBRARY_ABI != UnknownABI` part and letting it use the `gen_constants.jl` file and I confirm the constants that get generated are identical to what is in `src/consts/mpich.jl`, so I guess that's good. 

Next, I try and run a simple test program, but I get the following segfault every time:

```
$ srun -n 1 julia -e "using MPI"

*** Error in `/global/homes/m/marius/bin/julia': corrupted double-linked list (not small): 0x0000000000d0dcb0 ***

signal (6): Aborted
in expression starting at none:1
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
__libc_message at /lib64/libc.so.6 (unknown line)
malloc_printerr at /lib64/libc.so.6 (unknown line)
_int_free at /lib64/libc.so.6 (unknown line)
_ZN4llvm19ReachingDefAnalysis13releaseMemoryEv at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
_ZN4llvm13PMDataManager8freePassEPNS_4PassENS_9StringRefENS_19PassDebuggingStringE at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
_ZN4llvm13PMDataManager16removeDeadPassesEPNS_4PassENS_9StringRefENS_19PassDebuggingStringE at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /global/u1/m/marius/src/julia-1.4/usr/bin/../lib/libLLVM-8.so (unknown line)
```

I am on Julia 1.4 (have tried both official binaries and compiled from source with GCC), MPI v0.13.0,  gcc/8.3.0, mvapich2/2.3.2 (latter two loaded from modules on the cluster). 

I should also mention that compiling and running an MPI hello world example from eg [here](https://mpitutorial.com/tutorials/mpi-hello-world/) works fine, so seems tied to Julia. 

Any suggestions? Thanks.

**Comment by simonbyrne** [comment]
I haven’t had a lot of success with MVAPICH:  I managed to get it working once, but it required some environment variables to be set (I can’t remember exactly what). Does your cluster provide a different MPI implementation you can use?

**Comment by marius311** [comment]
Thanks for the quick reply. It does have also have [OpenMPI+UCX](https://docs-dev.nersc.gov/cgpu/software/#openmpi-ucx). I had managed to convince myself that their MVAPICH is "CUDA-aware" which is what I need. I haven't also checked for their OpenMPI+UCX (don't really know what UCX is) but I will take a look.

**Comment by simonbyrne** [comment]
UCX is the underlying communication library used by OpenMPI. If compiled correctly, it is CUDA aware (it is what we use ourselves).

**Comment by marius311** [comment]
Thanks for the tip, looks like the OpenMPI implementation works. I'll close this issue since I'm guessing getting MVAPICH working isn't high priority for this repo, although feel free to reopen.

**Comment by simonbyrne** [comment]
So I think I may have got it working on our cluster by setting the environment variables:
```
export MV2_USE_GDRCOPY=0
export MV2_USE_CUDA=1 
```
but I still got some warnings suggesting it wasn't configured correctly. If anyone does have success with MVAPICH, please do chime in here.

**Comment by simonbyrne** [comment]
By the way, if you want to check whether your MPI is CUDA-aware, you can try running the test suite with the environment variable `JULIA_MPI_TEST_ARRAYTYPE=CuArray`
