### ISSUE TITLE
Don't invalidate the cache with `build MPI` if nothing changes

### ISSUE THREAD

**Issue by vchuravy** [JuliaParallel/MPI.jl#388]
Currently we always update `deps.jl`, Even if nothing in the configuration has changed https://github.com/JuliaParallel/MPI.jl/blob/b16fc92474fa070712d2ff8b1af5c36ecd09cfa6/deps/build.jl#L202

In my scripts I often write:

```sh 
julia -e 'using Pkg; pkg"instantiate"; pkg"build MPI"'
julia -e 'using Pkg; pkg"precompile"'
```

To make sure that changes to the MPI environment are being picked up. We should cache the configuration and avoid recreation of `deps.jl` if nothing of import has changed.

**Comment by simonbyrne** [comment]
Fixed by #420.
