### ISSUE TITLE
2 minor typos in `collective.jl`

### ISSUE THREAD

**Issue by amartinhuertas** [JuliaParallel/MPI.jl#394]
Dear `MPI.jl` developers,

I am not wrong, I guess that in the following two lines of code:

https://github.com/JuliaParallel/MPI.jl/blob/master/src/collective.jl#L853
https://github.com/JuliaParallel/MPI.jl/blob/master/src/collective.jl#L856

`sendbuf` should actually be `buf`. 

I am indeed obtaining `UndefVarError: sendbuf not defined` when calling these functions.

I can do a PR and fix it if u find it useful.

@amartinhuertas

**Comment by simonbyrne** [comment]
Yes, you are correct. A PR would be most welcome!

**Comment by amartinhuertas** [comment]
> Yes, you are correct. A PR would be most welcome!

I already triggered the PR! More details at https://github.com/JuliaParallel/MPI.jl/pull/396

**Comment by simonbyrne** [comment]
Fixed by #396.
