### ISSUE TITLE
How to choose a specific MPI among multiples available on cluster

### ISSUE THREAD

**Issue by kibaekkim** [JuliaParallel/MPI.jl#40]
I am working on a cluster that has multiple MPI libraries (including MPICH and OpenMPI). Is there any way (or a function) that I can choose a specific MPI library?

**Comment by eschnett** [comment]
MPI is configured via cmake. I assume that you can set `PATH` to point to your MPI implementation. <http://www.cmake.org/cmake/help/v3.0/module/FindMPI.html> should have more details -- e.g. setting `MPI_C_COMPILER=/your/desired/mpicc` should work.

**Comment by ViralBShah** [comment]
Perhaps we should document this in the README?

**Comment by eschnett** [comment]
Does it actually work? In writing the reply above, I drew from my experience with clusters and the documentation, but I didn't try it myself... @kibaekkim, did you resolve the issue?

**Comment by kibaekkim** [comment]
Thanks for your suggestion.
My issue was the following. I observed that Julia always called OpenMPI whereas I need to call MPICH, even though "which mpirun" points to MPICH. More interestingly, on the same cluster, this did not happen to other users, for whom Julia called MPICH to run application. 
Here are what I tried. I unloaded all the MPI modules and set the environment variables (MPI_<LANG>_COMPILER) to what I want to hook (MPICH). Then I tried the following several things:
1) Pkg.build("MPI")
2) re-configure cmake; make; make isntall
3) Pkg.rm("MPI"); rm -rf $JULIA_PKGDIR/v0.3/MPI; Pkg.add("MPI");
4) rm -rf $JULIA_PKGDIR; Pkg.add("MPI");
The first three did not work, but only #4 works.

**Comment by eschnett** [comment]
This is now possible by setting the two environment variables
```
JULIA_MPI_INCLUDE_PATH
JULIA_MPI_LIBRARIES
```
which set the respective cmake flags.

**Comment by eschnett** [comment]
I assume the solution described above suffices.

**Comment by lcw** [comment]
@eschnett Should we also allow all the variables found in `cmake --help-module FindMPI` to be set in the `.juliarc` file?  I don't think that just `JULIA_MPI_INCLUDE_PATH` and `JULIA_MPI_LIBRARIES` will be enough for all MPI installations.  For my cmake the variables would be
```
 MPI_Fortran_COMPILER        MPI Compiler wrapper for <lang>
 MPI_Fortran_COMPILE_FLAGS   Compilation flags for MPI programs
 MPI_Fortran_INCLUDE_PATH    Include path(s) for MPI header
 MPI_Fortran_LINK_FLAGS      Linking flags for MPI programs
 MPI_Fortran_LIBRARIES       All libraries to link MPI programs against
```

Do we also need to include `CMAKE_Fortran_COMPILER` and friends?  Maybe we just need a generic way of passing CMake variables to the build scipt.

**Comment by eschnett** [comment]
@lcw Let's add the variables you need, and then wait a bit to see what others need before thinking about a generic mechanism.

When Julia is configured, it uses a particular Fortran compiler. Is this the same you're using to configure MPI? Should Julia remember this choice? I think the executables that `MPI.jl` creates to extract information from the MPI library are independent of Julia, so in principle there doesn't need to be any connection.

**Comment by eschnett** [comment]
@lcw The branch `eschnett/configure` adds environment variables, as usual with a `JULIA_` prefix, i.e. `JULIA_MPI_Fortran_COMPILER` etc., for your requested `cmake` options. Can you test this branch?

**Comment by lcw** [comment]
Your branch seems to work for setting these variables.

I think we still want to be able to set `CC` and `FC` environment variables (or equivalently `CMAKE_C_COMPILER` and `CMAKE_Fortran_COMPILER` CMake variables).  The trick to `FindMPI` that we are using is that the compiler CMake finds (from `CC` and `FC` or `CMAKE_C_COMPILER` and `CMAKE_Fortran_COMPILER`) must match what is used by the `mpicc` and `mpif90` wrappers.  If not, things may not work.  See the discussion here <https://cmake.org/pipermail/cmake/2012-June/050991.html> for a little more detail on how `FindMPI` should be used.
