### ISSUE TITLE
MPI Julia Issue

### ISSUE THREAD

**Issue by rajexplo** [JuliaParallel/MPI.jl#402]
Hello everybody;
I am running MPI API for julia and while there is the exception all the process do not get killed and jobs keep on running..
Also How to use MPI across the nodes and in node parallelization using ```everywhere```?

Thanks in advance, I will appreciate for your response.

**Comment by simonbyrne** [comment]
What version of MPI.jl are you using? There was an issue (#390) which was fixed in v0.14.2.

> Also How to use MPI across the nodes and in node parallelization using `everywhere`?

MPI.jl is distinct from Julia's `Distributed` library: if you want to use them together, see [MPIClusterManagers.jl](https://github.com/JuliaParallel/MPIClusterManagers.jl).

**Comment by rajexplo** [comment]
@simonbyrne Thank you!
I am using ```MPI v0.11.0```. I will try to update it and test it with it.

**Comment by simonbyrne** [comment]
Great, please re open if you’re still seeing the issue.
