### ISSUE TITLE
JULIA_MPIEXEC_ARGS should work consistently if installed with system or JLL MPI version

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/MPI.jl#410]
There maybe a good reason for the behavior to change given a system installed `mpiexec` vs a JLL one, however I think it would be preferable if (most of) the interfaces aligned if possible. 

XRef: https://github.com/CliMA/ClimateMachine.jl/commit/cc171602b68fc86400e29dbac20a2145eb63fc57#r40702136

**Comment by simonbyrne** [comment]
I was trying to move away from global environment variables as config options, but I can see the utility here.
