### ISSUE TITLE
Provide full path to MPI library and MPI include directory

### ISSUE THREAD

**Issue by sloede** [JuliaParallel/MPI.jl#425]
Over at [P4est.jl](https://github.com/trixi-framework/P4est.jl) we are working on adding support for p4est compiled with MPI. For this to be useful in a real-world setting, we also need to be able to swap out the underlying p4est library, similar to how MPI.jl allows to choose different MPI backends at package build time.

However, at the moment we are facing the challenge that we need the full path to the underlying MPI library, and to its include directory, such that we can auto-generate the C bindings with [CBindingGen.jl](https://github.com/analytech-solutions/CBindingGen.jl) (cf. trixi-framework/P4est.jl#10). One possible solution would be to query MPI.jl for these values, as for a sane MPI setup, the MPI backend used in MPI.jl and P4est.jl should be in sync. Thus I am wondering if it would be possible for MPI.jl to export the full path to the library and the include directory for the MPI backend, so that we could just use those values when generating the bindings for p4est? Alternatively, do you see another possible solution to this issue that we have not thought of?

**Comment by simonbyrne** [comment]
Unfortunately we don't have a good solution for this at the moment. You should be able to get the path of the library via
```julia
using MPI, Libdl
dlpath(MPI.libmpi)
```

There isn't a great way to get the include path however (MPI.jl doesn't require the C headers unless it needs to fall back on generating the C genconst script). You could try something like:
```julia
MPI_PATH = dirname(dirname(normpath(dlpath(MPI.libmpi))))
MPI_INCLUDE_PATH = get(ENV, "JULIA_MPI_INCLUDE_PATH", joinpath(MPI_PATH,"include"))
```

**Comment by sloede** [comment]
Thanks @simonbyrne for your helpful reply! This seems to be a good solution for all jll MPI backends and typical HPC cluster installations (where a library is installed to a dedicated prefix). It won't work on user workstations (e.g., OpenMPI on Ubuntu will definitely fail), but this is then just a matter of good documentation.

If you're interested, I'll try to report back here in a few days how this worked out for P4est.jl; otherwise please feel free to close this issue.

**Comment by sloede** [comment]
I'd like to report that it seems to work like you proposed, and we adopted it into [P4est.jl](https://github.com/trixi-framework/P4est.jl) (see https://github.com/trixi-framework/P4est.jl/blob/ff2b9893e4697ab21a916c00c3f3f9d350fc1ccf/deps/build.jl#L128-L131):
```julia
  if isempty(mpi_include)
    mpi_include = joinpath(dirname(dirname(normpath(dlpath(MPI.libmpi)))), "include")
    println("Use MPI include path based on path to `MPI.jl`'s `libmpi`")
  end
```
Thanks again for your input on this!
