### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPI.jl#43]
We need to catch up with the recent changes on master... 

````
julia> import MPI
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in depwarn at ./deprecated.jl:40
 in int32 at deprecated.jl:29
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:51
WARNING: int(x) is deprecated, use Int(x) instead.
 in depwarn at ./deprecated.jl:40
 in int at deprecated.jl:29
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:51
````

**Comment by ViralBShah** [comment]
We need to also update Compat.jl and make this backwards compatible.

**Comment by psanan** [comment]
This would be quite  helpful for us since on larger core counts the deprecation warnings produce a substantial amount of text!

**Comment by jakebolewski** [comment]
You can turn off deprecations  by passing the '--deepwarn=no' command line flag to the julia process.  Also beware if you are profiling any code that could throw deprecation warnings as you will encounter significant slowdowns.

**Comment by psanan** [comment]
Thanks - I managed to google that flag seconds ago! Many thanks for the profiling tip: that will very likely end up having saved us time.

**Comment by jakebolewski** [comment]
turning off throwing the warnings removes the performance hit so it is usually the best way to get deterministic timings

**Comment by bdeonovic** [comment]
@jakebolewski note the misspelling above it should be `--depwarn=no`

**Comment by jakebolewski** [comment]
edited, thanks
