### ISSUE TITLE
Yell if run under a different MPI

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaParallel/MPI.jl#430]
I was initially confused by the fact that I ran my julia/MPI script like `mpiexec julia test.jl` and everything worked fine... except that it used only one process. Is it possible to raise an error/warning if the executing MPI doesn't match MPI.jl's?

**Comment by simonbyrne** [comment]
Not that I know of, unfortunately.

**Comment by simonbyrne** [comment]
We might be able to come up with some ad-hoc rules, e.g. if the environment variables `MPI_LOCALNRANKS` (set by the MPICH launcher) or `OMPI_COMM_WORLD_SIZE` (set by the Open MPI launcher) is different than `MPI.Comm_rank(MPI.COMM_WORLD)`, then throw an error?

**Comment by antoine-levitt** [comment]
That'd be cool : it doesn't have to be 100% foolproof, just a friendly hint that you're doing something wrong. I can make a PR with that. Is that still a valid usage (and therefore just a warning) or an error?

**Comment by simonbyrne** [comment]
That would be great thanks. We do something similar when people appear to be using the default MPI binary on a cluster:
https://github.com/JuliaParallel/MPI.jl/blob/20424263680e0c1339ea1f72814ad6cf25cef7b3/deps/build.jl#L158-L161
You can copy that.

**Comment by giordano** [comment]
The [`mpiexecjl`](https://juliaparallel.github.io/MPI.jl/v0.16/configuration/#Julia-wrapper-for-mpiexec) wrapper should also help with this.
