### ISSUE TITLE
Code question - why do you use @view?

### ISSUE THREAD

**Issue by lyon-fnal** [JuliaParallel/MPI.jl#445]
Hi, I have a little question about your test code. In `test_shared_win.jl` you have

https://github.com/JuliaParallel/MPI.jl/blob/5d6fae8dc483fd7b23ecf524a0f274ac3e5d2e2a/test/test_shared_win.jl#L39

Why do you use the `@view` (which makes you use the surrounding parentheses) on that line (and the next one)? I thought that directly setting a slice of an array does not make a copy. Though you are broadcasting, so perhaps that matters?

Thanks in advance for insights. I'm trying to learn efficient Julia and I haven't seen a construct like this elsewhere. -- Adam

**Comment by simonbyrne** [comment]
I think you are correct here: looking at how the code expands, it does appear that using `X[:,1] .= ....` calls `Base.dotview(X,:,1)`.

I'm not sure why it is written this way: it was added by @JobJob in https://github.com/JuliaParallel/MPI.jl/commit/9550216e2654aa569144d81afbcf7010ea4a058e.

**Comment by JobJob** [comment]
Yeah good question, I don't remember why I coded it like that - probably I just wasn't 100% about the semantics of `X[:,1] .= ...` at the time, so wanted to be explicit about it to be sure, or it's possible I was just double checking that it also worked with an explicit view and the code stayed in.

**Comment by lyon-fnal** [comment]
Ok - thanks for the clarification! BTW - this example of using shared memory with MPI is really good - I'm planning to use it in my code.

**Comment by JobJob** [comment]
Great, glad to hear!

And cheers Simon for the clean up job.
