### ISSUE TITLE
Remove `dlopen` in `__init__`

### ISSUE THREAD

**Issue by vchuravy** [JuliaParallel/MPI.jl#447]
I am wondering if we are still needing this after switching to the `ccall((libmpi, :MPI_))` style.

https://github.com/JuliaParallel/MPI.jl/blob/91d95034d06d368ec9c7cdc89a8f57f72bcf393e/src/MPI.jl#L64

**Comment by simonbyrne** [comment]
I think we need the `Libdl.RTLD_GLOBAL` so that the globally symbols are accessible.
