### ISSUE TITLE
Using Arrow.Table with MPI.jl

### ISSUE THREAD

**Issue by calebwin** [JuliaParallel/MPI.jl#461]
`Arrow.Table` allow for zero-copy deserialization of dataframes:
```julia
function serialize(df::AbstractDataFrame)
    io = IOBuffer()
    Arrow.write(io, obj)
    view(io.data, 1:position(io))
end

function deserialize(bytes::Vector{UInt8})
    Arrow.Table(bytes)
end
```
 I want to be able to use this with MPI operations on `Buffer`, `RBuffer`, `VBuffer`. Is there some function like `Base.cconvert` I can implement to enable me to easily pass around dataframes?

**Comment by simonbyrne** [comment]
I hadn't really thought of an interface for this, but it should be possible to just add these definitions to `MPI.serialize`/`MPI.deserialize`.

**Comment by calebwin** [comment]
Okay.. I'm kind of confused about what can be passed to MPI. It looks like a `Ptr` or `Ref` can be passed but can't any Julia object be wrapped in a `Ptr` or `Ref`? Does passing a `Ptr` to an object result in it not being copied within the same node or process?

**Comment by calebwin** [comment]
I'm building a distributed computing framework on top of MPI.jl and I need to be able to communicate various different kinds of data:

- `AbstractArray` containing `isbitstype` data (checking `isbitstype` is the only way of knowing for sure that the data is equally sized)
- `AbstractArray` containing inequally-sized data (e.g., `ArrowList` containing strings)
- `Arrow.Table` - This can be serialized/deserialized without copying by using `Arrow.write` to an IOBuffer and then `Arrow.Table`
- Other `isbitstype` data
- Everything else (think unstructured data like dictionaries - we still want to be able to do reductions over these)

I'm trying to determine the best way to do the ser/de for this communication with MPI:

- `serialize` and `deserialize` everything - This would be wildly inefficient for things like reductions for summing columns of an array and doesn't take advantage of zero-copy deserialize
- `Arrow.write`/`.Table` for dataframes, pass in all values or arrays of values that are `isbitstype` as-is, `serialize/deserialize` everything else
- some other option I'm not thinking about?

Do you think I'm thinking about this the right way?

**Comment by simonbyrne** [comment]
Ah, OK. MPI is fundamentally designed around communicating sequential arrays of fixed-length datatypes (it is possible to support non-sequential data via custom datatypes, but they still have to be fixed length).

If you have anything else, you need to first serialize it somehow to a sequential buffer: this is what the lowercase functions do: at the moment only `MPI.send`, `MPI.recv`, and `MPI.bcast` are defined. I'd be happy to add more (e.g. to match mpi4py). While it would be nice to unify these, I haven't come up with a clear and consistent way to do this.

One annoying thing is that MPI also generally assumes both sides of the communicator know the length of the buffer to be communicated: for `MPI.recv` we can get around this [by using `MPI.Probe`](https://github.com/JuliaParallel/MPI.jl/blob/bd55b74edc17f607618aa5f3b663b67994f011b5/src/pointtopoint.jl#L311), but collective operations would require another round of communication to first communicate the lengths, e.g. [`bcast` has to call `MPI.Bcast!` twice](https://github.com/JuliaParallel/MPI.jl/blob/bd55b74edc17f607618aa5f3b663b67994f011b5/src/collective.jl#L58-L62). 

Unfortunately I don't know of any great solutions to what you want to do, but I am open to interface changes if it would make things easier.

Another option might be something more lower-level, like [UCX.jl](https://github.com/JuliaParallel/UCX.jl)?

**Comment by calebwin** [comment]
Thanks for the response. That makes sense and I can work with that but is _any_ fixed-length datatype supported? Is there a good way to check for what is supported or should I just check `isbitstype`?

**Comment by simonbyrne** [comment]
Any `isbitstype` array should work. `Ref` and `Ptr` are treated as a single-element array.

**Comment by calebwin** [comment]
Thanks, that makes sense. Sorry to be bugging you with all these questions but - if I'm passing multi-dimensional arrays holding simple C/isbits-typed data, will they get serialized and deserialized properly with the deserialized data having the proper dimensions? I'm thinking about this for a call to `Allgather` but also for a call to `Alltoallv` where it looks like I need to pack a bunch of arrays into a `VBuffer`...

**Comment by simonbyrne** [comment]
If you're using the uppercase functions, then there is no serialization: MPI just communicates the raw bytes of the array. Both sides of the communication need to know the size and datatype, and generally you need to preallocate the receive buffer (except fora few cases where we can determine the size of the receive buffer from the send buffer)

**Comment by simonbyrne** [comment]
Not sure if there are any concrete changes to be made here. If so, please feel free to re-open.
