### ISSUE TITLE
An example on how to `Scatterv!` and `Gatherv!` a two-dimensional array?

### ISSUE THREAD

**Issue by francispoulin** [JuliaParallel/MPI.jl#469]
I have managed to use `Bcast!` successfully when I define it to be a `Vector` or a `Matrix`.  At the moment I'm stuck because I want to split (for example) a `5x3` matrix and I want to split it between two cores: the first should be `3x3` and the other `2x3`.  However, I need to define this in one object.

I figured out how to do this using `Vector{Matrix{Float64}}(undef, comm_size)` but then when I try and use `MPI.Bcast!` it complains that this is not `isbitstype`, which I'm sure is true.  I've only been able to successfully broadcast `Vector` or `Array`, but neither of these can describe the split that I want.

Can someone help me figure out what buffers `Bcast!` accepts and how I might be able to produce this object?

The error I get is copied below.

```
ERROR: LoadError: ArgumentError: Type must be isbitstype
Stacktrace:
 [1] MPI.Datatype(::Type{Matrix{Float64}}; commit::Bool)
   @ MPI.Types ~/.julia/packages/MPI/26D0s/src/datatypes.jl:267
 [2] MPI.Datatype(::Type{Matrix{Float64}})
   @ MPI.Types ~/.julia/packages/MPI/26D0s/src/datatypes.jl:266
 [3] MPI.Buffer(arr::Vector{Matrix{Float64}})
   @ MPI ~/.julia/packages/MPI/26D0s/src/buffers.jl:138
 [4] Bcast!(data::Vector{Matrix{Float64}}, root::Int64, comm::MPI.Comm)
   @ MPI ~/.julia/packages/MPI/26D0s/src/collective.jl:39
 [5] top-level scope
```

**Comment by francispoulin** [comment]
Yes, I first want to `Scatterv!` and then `Gatherv!`.  As a check I was trying to do `Bcast!` as a simple test and that failed.  I figured if that failed then others would fail.  

The example that I'm trying to translate is in python and [here.](https://stackoverflow.com/questions/36025188/along-what-axis-does-mpi4py-scatterv-function-split-a-numpy-array/36082684#36082684).  

My sample code that does produce the correct results but needs some work is [here](https://github.com/francispoulin/Linear-Stability-Calculators/blob/main/QuasiHydrostataic/Julia/test_2D_array.jl).  In this example I need to assume that the number of rows is a multile of the comm size, but I want to generalize that.  

I was also thinking that others might benefit from this and perhaps this could become an example, somewhere.  

I am taking transposes but I don't think that helps me to avoid the problem I'm having.  Maybe custom Datatypes is something I should learn more about.  Can you help direct me to an example I can read more about?

**Comment by simonbyrne** [comment]
I've added an example in #470 which I hope addresses your questions. Please chime in there if something is not clear, or you have any suggestions.

My larger point is that you shouldn't need `Bcast` (since only the root rank needs to know all the sizes), instead you can get away with a `Scatter` of the array sizes. The other issue is that Julia stores arrays in column-major order, so you need to distribute over the last dimension of the array.

**Comment by francispoulin** [comment]
Thanks @simonbyrne for making this example.  It's very helpful.  I have some thoughts but I'll separate them so they are hopefully easier to read.

`split_count` needs some work?

One thing that I noticed is the split_count does not seem to distribute things as I might exepect.  Below are some samples and you can see that sometimes it doesn't use some cores at all.

```
julia> split_count(10,6)
6-element Vector{Int64}:
 2
 2
 2
 2
 2
 0

julia> split_count(10,7)
7-element Vector{Int64}:
 2
 2
 2
 2
 2
 0
 0

julia> split_count(10,8)
8-element Vector{Int64}:
 2
 2
 2
 2
 2
 0
 0
 0

julia> split_count(10,9)
9-element Vector{Int64}:
 2
 2
 2
 2
 2
 0
 0
 0
 0
```

I wrote a version of the code that I believe uses all cores, also computes the displacements, but don't pretend this is good julia programming style.  I now see that I don't actually need `comm` to be passed and and `comm_size` could, and should, be replaced with `n`, like you did in your example.  

```
function find_split_sizes(N, comm_size, comm)

    counts = zeros(Int64, comm_size)
    displs = zeros(Int64, comm_size)

    if rank == 0
        counts_guess = Int64(div(N, comm_size, RoundDown))
        Remainder    = Int64(N - counts_guess * comm_size)
        counts[:]   .= counts_guess

        for i in 1:Remainder
            counts[i] += 1
        end

        displs[:] = cumsum(append!([0], counts))[1:comm_size]
    end

    MPI.Bcast!(counts, 0, comm)
    MPI.Bcast!(displs, 0, comm)

    return counts, displs
end
```

**Comment by francispoulin** [comment]
Your larger point is well taken, `Bcast` was not the main issue, it was of course `Scatterv!`.  I was playing with that to learn to see what objects I could pass but that was a distraction.  Sorry about that.

**Comment by simonbyrne** [comment]
Thanks, I made a small tweak to the function, it should give better splits now.

Note that you don't need to compute the displacements manually, as the `VBuffer` constructor will do that for you.

**Comment by francispoulin** [comment]
Thanks for tweaking the function.

Also, I agree that you don't have to compute the displacements and I was doing it to make sure that I know how but I will avoid this in the future, to make things easier on myself.

**Comment by francispoulin** [comment]
In line 52 its said that we don't need to define `sizes` or `output_vbuf` on non-root processes.  However, when I commented out either line 53 or 54 I got an error.  One of the cases is below.  This seems to suggest that you do need to define these on non-root processes, or I am missing something?

```
ERROR: ERROR: LoadError: LoadError: UndefVarError: test_vbuf not definedUndefVarError: test_vbuf not defined
```

**Comment by simonbyrne** [comment]
> In line 52 its said that we don't need to define `sizes` or `output_vbuf` on non-root processes. However, when I commented out either line 53 or 54 I got an error. One of the cases is below. This seems to suggest that you do need to define these on non-root processes, or I am missing something?

Thanks. I was being imprecise: the variables need to be defined (otherwise it isn't valid Julia), but they can be assigned `nothing` (as they are ignored by MPI).

**Comment by francispoulin** [comment]
I guess one important thing I was missing is you don't have to construct `local_test` beforehand.  I was trying to build that and was trying all sorts of things but nothing was working.  Now I see the solution is actually very nice.  You don't need to specify it on `root` and it becomes of different sizes for each process.  Very sorry I didn't figure that out myself.

Also, the use of `VBuffer` is very helpful.  

It is rather critical to know that julia stores arrays column-major wise.  I can build my arrays appropriately to split in terms fo the last dimension.

This example is very clear and I feel like I understand it pretty well.  To test my knowledge I will try doing splitting in a 3D array.

Thanks a lot @simonbyrne for putting this together and I'm very happy to know this is going to make it's way into the docs, as I imagine others will benefit from it as well.

**Comment by francispoulin** [comment]
I changed the title to make ti more descriptive and will close the issue.

**Comment by francispoulin** [comment]
@simonbyrne 

I was able to get a 3D example working very easily and know that I can do any higher dimension easily enough.

However, when I tried to the the 1D case I found something a bit weird.  Code copied below.  

The `Scatterv!` did not work directly because of the following error.  I found that if I put in the `[1]` it runs but I'm not really sure why.  Is there a better fix for this case?

```
ERROR: ERROR: LoadError: LoadError: MethodError: no method matching zeros(::MethodError: no method matching zeros(::Type{Float64}, ::Vector{Int64})Type{Float64}, ::Vector{Int64})
Closest candidates are:
  zeros(::Type{T}, !Matched::Union{Integer, AbstractUnitRange}...) where T at array.jl:499
  zeros(::Type{T}, !Matched::Tuple{}) where T at array.jl:507
  zeros(::Type{T}, !Matched::Tuple{Vararg{Integer, N}}) where {T, N} at array.jl:502
```

```
...
if rank == root
    N = 7

    test = Float64[i for i = 1:N]
    output = similar(test)

    # Julia arrays are stored in column-major order, so we need to split along the last dimension
    # dimension
    N_counts = split_count(N, comm_size)

    # store sizes in 2 * comm_size Array
    sizes = vcat(N_counts')

    # store number of values to send to each rank in comm_size length Vector
    counts = vec(prod(sizes, dims=1))

    test_vbuf = VBuffer(test, counts) # VBuffer for scatter
    output_vbuf = VBuffer(output, counts) # VBuffer for gather
else
    # these don't need to be defined on non-root processes
    sizes = nothing
    output_vbuf = test_vbuf = VBuffer(nothing)
end

if rank == root
    println("Original matrix")
    println("================")
    @show test sizes counts
    println()
    println("Each rank")
    println("================")
end 
MPI.Barrier(comm)

local_N = MPI.Scatter!(sizes, zeros(Int, 1), root, comm)
local_test = MPI.Scatterv!(test_vbuf, zeros(Float64, local_N[1]), root, comm)
...
```

**Comment by simonbyrne** [comment]
Note that `MPI.Scatter!(sizes, zeros(Int, 1), root, comm)` returns a vector of length 1. The 2-dimensional code was doing destructuring assignment, see https://docs.julialang.org/en/v1.7-dev/manual/functions/#destructuring-assignment, but without the comma it just does regular assignment and so `local_N` is now a vector instead of an integer.

You can still do destructuring assignment if you like, by
```
local_N, = MPI.Scatter!(sizes, zeros(Int, 1), root, comm)
local_test = MPI.Scatterv!(test_vbuf, zeros(Float64, local_N), root, comm)
```
or you could just have a single variables for all the sizes, and splat them into `zeros` (which would work for any dimension):
```
local_sizes = MPI.Scatter!(sizes, zeros(Int, 1), root, comm)
local_test = MPI.Scatterv!(test_vbuf, zeros(Float64, local_sizes...), root, comm)
```

**Comment by francispoulin** [comment]
Thanks @simonbyrne for the explaination, and the reference.  That is very helpful as well.
