### ISSUE TITLE
mpiexecjl test fails when it can't find julia on the path

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPI.jl#476]
I just installed MPI.jl and ran the tests and they failed. Perhaps something to do with how it finds the julia binary? I don't have it on my PATH.

```
/var/folders/rj/njz8jnv11637flz6vgnb6bz00000gp/T/jl_KNqmae/mpiexecjl: line 61: julia: command not found
mpiexecjl: Error During Test at /Users/viral/.julia/packages/MPI/E3Wer/test/mpiexecjl.jl:4
  Got exception outside of a @test
  failed process: Process(`/var/folders/rj/njz8jnv11637flz6vgnb6bz00000gp/T/jl_KNqmae/mpiexecjl --project=/var/folders/rj/njz8jnv11637flz6vgnb6bz00000gp/T/jl_KNqmae /Users/viral/julia/usr/bin/julia --startup-file=no -q /Users/viral/.julia/packages/MPI/E3Wer/test/../docs/examples/01-hello.jl`, ProcessExited(127)) [127]
```

**Comment by ViralBShah** [comment]
@giordano I was following your lead after merging MPICH 3.4.2 - and ran into this.

**Comment by giordano** [comment]
`julia` should be in the `PATH`.

**Comment by vchuravy** [comment]
Well you could use `Base.julia_cmd()`

**Comment by giordano** [comment]
But we aren't inside Julia 🙂

**Comment by ViralBShah** [comment]
Right but the full path to Julia can be used in the script that is generated.

**Comment by ViralBShah** [comment]
I see - this is a shell script. Maybe we should allow the path to julia to be passed as a command line argument? The test script that launches it can then use `Base.julia_cmd()` and that will ensure tests will work reliably and pick the right version of Julia.

**Comment by giordano** [comment]
Ok, so we could run julia in the shell wrapper with
```sh
${JULIA_CMD:-julia}
```
and run the test by setting:
```julia
ENV["JULIA_CMD"] = Base.julia_cmd()
```
Does it sound good?  Any preference for the name of the environment variable?  Is there some sort of standards?

**Comment by ViralBShah** [comment]
I think `JULIA_HOME` used to be a thing in the past. Maybe good to use that? Here's something I found:

https://julia-doc.readthedocs.io/en/latest/manual/environment-variables/
