### ISSUE TITLE
Travis Testing

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/MPI.jl#48]
I'm trying to adapt the [Mpi4py travis file](https://bitbucket.org/mpi4py/mpi4py/src/fb17db87796943025c0f0ddfc849240e5132e8b0/.travis.yml?at=master), does overriding the default `before_install` conflict with the default `language: julia` config?

@tkelman, @ivarne it would be great if you could chime in here.

**Comment by tkelman** [comment]
> does overriding the default `before_install` conflict with the default `language: Julia` config?

[No.](https://github.com/tkelman/CoinOptServices.jl/blob/master/.travis.yml) You can do whatever you want in `before_install`.

**Comment by jakebolewski** [comment]
Ok, thanks.  It would be useful to update the docs. It is not clear which steps are able to be extended by the user without overriding the default config (or maybe this is in the language documentation somewhere for Travis?).

**Comment by tkelman** [comment]
The only section where overriding makes any difference is `script`, I believe

**Comment by jakebolewski** [comment]
Seems to be working, thanks @tkelman.

**Comment by lcw** [comment]
This is awesome!
