### ISSUE TITLE
More user-friendly MPI.Init

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/MPI.jl#484]
While C/C++/Fortran applications using MPI would call `MPI_Init` at the beginning of the program and that's it, in Julia it's more common that you may want to put `MPI.Init()` inside a function that you may call multiple times, especially when playing with it in the REPL.

To avoid calling `MPI_Init` multiple times, which isn't allowed, it's common to use a pattern like the following:
```julia
if !MPI.Initialized()
    MPI.Init()
end
```
([example 1](https://github.com/trixi-framework/Trixi.jl/blob/784650dbc903037c557202275cc885cf26dc78d2/src/auxiliary/mpi.jl#L19-L26), [example 2](https://github.com/JuliaMolSim/DFTK.jl/blob/d26aaea37a0b5f6dd9683ddcbaa4287183e7ebaf/src/common/mpi.jl#L4-L15), [example 3](https://github.com/eschnett/ADIOS2.jl/blob/1a3d52216fea306b63928217da584b45b768ebba/test/runtests.jl#L9-L13), [example 4](https://github.com/kibaekkim/DualDecomposition.jl/blob/b780adb9de630ba3769564f4c79403f5326f2e39/src/parallel.jl#L6-L8), [etc...](https://github.com/search?l=Julia&p=2&q=MPI.Initialized&type=Code)).

It'd be nice to have `MPI.Init` to automatically check whether MPI is already initialised and call `MPI_Init` only if it isn't the case.  However, @sloede pointed out on Slack that

> it would be necessary to support the different multi-threading settings and make sure that you either abort or warn if the requested threading level is not supported - or if an earlier call to MPI_Init did set a lower level than what you need.

Could do the same also for `MPI.Finalize`

**Comment by simonbyrne** [comment]
What did you mean by 

> Could do the same also for `MPI.Finalize`

**Comment by giordano** [comment]
I usually just trust `MPI.jl` does its job and I don't use `MPI.Finalize` directly :grin:  But see examples 1 and 3 in

> ([example 1](https://github.com/trixi-framework/Trixi.jl/blob/784650dbc903037c557202275cc885cf26dc78d2/src/auxiliary/mpi.jl#L19-L26), [example 2](https://github.com/JuliaMolSim/DFTK.jl/blob/d26aaea37a0b5f6dd9683ddcbaa4287183e7ebaf/src/common/mpi.jl#L4-L15), [example 3](https://github.com/eschnett/ADIOS2.jl/blob/1a3d52216fea306b63928217da584b45b768ebba/test/runtests.jl#L9-L13), [example 4](https://github.com/kibaekkim/DualDecomposition.jl/blob/b780adb9de630ba3769564f4c79403f5326f2e39/src/parallel.jl#L6-L8), [etc...](https://github.com/search?l=Julia&p=2&q=MPI.Initialized&type=Code)).

They use the pattern:
```julia
if !MPI.Finalized()
    MPI.Finalize()
end
```
