### ISSUE TITLE
Accessing underlying MPI_Comm from CxxWrap

### ISSUE THREAD

**Issue by williamfgc** [JuliaParallel/MPI.jl#487]
This question came up at Julia for HPC BoF at JuliaCon 2021. We'd like to build Julia bindings for the [ADIOS2](https://github.com/ornladios/ADIOS2) library using `CxxWrap` and `MPI.jl`. 

In the Python bindings using pybind11, the MPI communicator is exposed to C or C++ via the `<mpi4py/mpi4py.h>` header function `PyMPIComm_Get` so a pybind11 Python object can be cast as a C `MPI_Comm` (regardless of MPI implementation, `int` or `void*`) and used internally, see [here](https://github.com/ornladios/ADIOS2/blob/master/bindings/Python/py11glue.cpp#L67). 

The question is if such mechanism is possible and a working example would be even better. Thanks in advaced.

**Comment by simonbyrne** [comment]
I haven't used CxxWrap, but for ordinary C functions you can just use `MPI.MPI_Comm` as the argument type in `ccall` and pass the regular `MPI.Comm` object (which is the Julia wrapper), e.g. see:
https://github.com/JuliaParallel/MPI.jl/blob/bd7e079e7fcd62a8e1990b8fa250282d3a03b0bf/src/comm.jl#L65-L69
