### ISSUE TITLE
OpenMPI travis tests fail

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/MPI.jl#49]
Needs more investigation.

**Comment by lcw** [comment]
Are you sure it used to work.  The test used to fail for me.  For example, look at the log for the build <https://travis-ci.org/JuliaParallel/MPI.jl/jobs/53801874> .  Even though the travis build is green some of the tests failed.  I have not been able to figure out why.

**Comment by jakebolewski** [comment]
No you are right.  I was being lazy and not looking through the old Travis history.

**Comment by lcw** [comment]
Thanks for your work getting MPICH to work with travis.  It is also better now that we have the tests running from inside Julia instead CMake so that we make sure the correct julia binary is called.
