### ISSUE TITLE
Don't redefine `MPI_UNDEFINED` to 0

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#499]
The function `Testany!` and `Waitany!` return the request array index `0` to indicate that no request was completed. This differs from the MPI standard, which specifies that these functions should return `MPI_UNDEFINED`.

I think we should stick to the MPI standard here and instead return `MPI_UNDEFINED`. People familiar with the standard (e.g. me) will be surprised by this deviation, and I don't think we gain much by deviating from the standard.

**Comment by simonbyrne** [comment]
Fixed by #479
