### ISSUE TITLE
MPI.jl fails with devel. version 0.4.0-dev+3978 (2015-03-24 04:36 UTC)

### ISSUE THREAD

**Issue by mcreel** [JuliaParallel/MPI.jl#50]
Hello all, 
The MPI package does not seem to be working with recent devel versions. This has been going on for a few days, I have waited a bit before reporting to see if it would be resolved. The following is on Debian testing, AMD64,
 
michael@pelican:~/julia$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3978 (2015-03-24 04:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit c4b5397* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of SHA...
INFO: Updating cache of URIParser...
INFO: Computing changes...
INFO: Upgrading SHA: v0.0.3 => v0.0.4
INFO: Upgrading URIParser: v0.0.4 => v0.0.5

julia> import MPI
ERROR: LoadError: LoadError: UndefVarError: RTLD_LAZY not defined
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/michael/.julia/v0.4/MPI/src/../deps/src/compile-time.jl, in expression starting on line 1
while loading /home/michael/.julia/v0.4/MPI/src/MPI.jl, in expression starting on line 3

julia>

**Comment by scidom** [comment]
Try:

* `Pkg.rm("MPI")` and then ideally remove ~/.julia/v0.4/MPI,
* `Pkg.clone("https://github.com/JuliaParallel/MPI.jl.git")`,
* `Pkg.build("MPI")`.

Does it help patch things up till the package's METADATA gets sorted?

**Comment by mcreel** [comment]
Yes, that seems to have solved the problem. Thanks!

**Comment by scidom** [comment]
You're welcome @mcreel.

**Comment by amitmurthy** [comment]
cc: @dmbates - this was the issue we were seeing at JuliaCon. Solved for me with the latest versions of Julia, BinDeps and MPI.jl
