### ISSUE TITLE
Bool handling

### ISSUE THREAD

**Issue by johnomotani** [JuliaParallel/MPI.jl#506]
The MPI standard has a Boolean type `MPI_C_BOOL` (see Table 3.2, p. 26 https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf). Should this be included explicitly in `datatypes.jl`? https://github.com/JuliaParallel/MPI.jl/blob/54cb06eaa3f965f0a9a18ab3d7e60b369a5b1d9c/src/datatypes.jl#L111-L134

I don't know if this would actually be useful... I came to the question looking for a bug, but found the bug in my own code, and can successfully create a shared array of `Bool` already. So this is just an FYI - feel free to ignore and close if it's not helpful!

**Comment by simonbyrne** [comment]
I think the reason I didn't was because I wasn't sure if they had matching sizes, but it does appear that they do.
Interestingly though, the Julia docs say that the Julia alias for `_Bool ` is `Cuchar`, not `Bool`, so I'm not 100% sure, but it should work.
