### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaParallel/MPI.jl#51]
There is [Microsoft MPI](https://www.microsoft.com/en-us/download/details.aspx?id=47259), would be great if this package would work in that environment.

@tkelman, I think you mentioned some interaction with MS on this?

**Comment by lcw** [comment]
As far as I know CMake supports finding MS-MPI, see for example the resent exchange on the CMake mailing list <http://www.cmake.org/pipermail/cmake/2015-March/059985.html>.  Since we use CMake to find the MPI libraries it might almost work out of the box.  There might be a few unixisms in the CMakeLists.txt that need to be cleaned up to make this work.

**Comment by tkelman** [comment]
So far the interaction with a member of the MS-MPI team has been at https://github.com/elemental/Elemental/issues/21, there's some discussion there about how to script and automate installation of MS-MPI which would be relevant here.

We haven't gotten things quite working there yet, but there are two directions - MS-MPI is primarily designed to work with MSVC (possibly also the Intel compilers on Windows but I'm not sure), we would need a handful of tweaks to get things running with MinGW for support with Fortran libraries and most of the way we build binaries in the Julia ecosystem.

**Comment by lcw** [comment]
Oh yea, I didn't think about Fortran.  Have a working Fortran compiler that can use MS-MPI is also a requirement.

**Comment by davidanthoff** [comment]
This is probably a stupid question, but why do we need to compile any C of Fortran code at all for this to work? Doesn't the Microsoft MPI installer just drop the msmpi.dll into system32, and then we need to call functions in there via ccall? I have very little experience with MPI, so bear with me if this doesn't make any sense...

**Comment by tkelman** [comment]
Unfortunately MS-MPI only gives you static libs, which is likely to be a bit of an issue for MPI.jl.

**Comment by davidanthoff** [comment]
I just installed it, and the binary installer seems to drop a dll into system32 called msmpi.dll...

**Comment by lcw** [comment]
Not a stupid question at all.  We use the fortran compiler to build a dynamic library that can be loaded from julia.

We also use the fortran compiler to get the values of the mpi constants, see <https://github.com/JuliaParallel/MPI.jl/blob/master/deps/make_f_const.f>.  I am open to alternatives to getting these values.

**Comment by davidanthoff** [comment]
Do these values change between MPI implementations? It's not a long list, we could just hand-code them into a julia file?

**Comment by lcw** [comment]
I believe, according to the standard, that these values can be different
implementation to implementation.  I don't know how different they are.

Unfortunately, MPI is only defined as an API.  There is no ABI standard.
Although some of the implementations are trying to be ABI compatible,
see <https://www.mpich.org/abi/>.

**Comment by davidanthoff** [comment]
I'm trying to hard-code the values from the MS implementation for now, should take long at all. Will report back.

**Comment by davidanthoff** [comment]
I got all the examples to run.

I did all of that based on the last tagged version. I then switched to master to create PR, but master seems to only run on julia 0.4, and I'm on 0.3... What is the best way to handle this? My sense is that master should use compat to be 0.3 compatible.

**Comment by davidanthoff** [comment]
See #52. Not complete at all, but it runs all the examples on my machine. The only thing I had to install was the Microsoft MPI redistribution.

**Comment by davidanthoff** [comment]
I've just rebased and fixed #52 and that PR should now be ready for review.

**Comment by davidanthoff** [comment]
And done with #52.
