### ISSUE TITLE
Using MPI with native threads causes large slowdown

### ISSUE THREAD

**Issue by sash-a** [JuliaParallel/MPI.jl#525]
I'm trying to run a hybrid MPI/OpenMP style program with julia's native threads package, but I'm seeing little speed or in the worst cases a large slowdown.

```
using BenchmarkTools: @btime, @benchmark
using Random

using ThreadPools
using Base.Threads
using MPI: MPI, Comm

# some minor utils for getting rank when using either a ThreadComm or and MPI Comm

struct ThreadComm end  # used for when thread only mode

# assumes comm is a nodecomm
noderank(comm::Comm) = MPI.Comm_rank(comm)
noderank(::ThreadComm) = 0
procrank(comm) = (noderank(comm) * Threads.nthreads()) + Threads.threadid()  # threads overall rank given all the nodes
nnodes(comm::Comm) = MPI.Comm_size(comm)
nnodes(::ThreadComm) = 1

f() = rand() ^ rand()

MPI.Init()
comm = MPI.COMM_WORLD
# comm = ThreadComm()

n = Threads.nthreads() * 9 / nnodes(comm)
ts = time_ns()
@qthreads for i in 1:n
    sleep(0.1)
end

println("[$(procrank(comm))] end: $(time_ns() - ts)")
```

`ThreadComm()` must be uncommented for threaded mode and run with `julia --project -t 24 scripts/btimesimple.jl`  
`MPI.Init()` and the line below is the MPI comm and is run with `mpiexec -N 3 julia --project -t 24 scripts/btimesimple.jl` (Note the capital N argument creating one mpi proc per node)

With MPI across 3 nodes I get a final time of: 1225670405ns  
With purely threaded I get a final time of: 1567280908ns

Since this is embarrassingly parallel and there is no communication I would expect much closer to 3x speedup. When running `f` instead of `sleep` I actually see a slowdown when using MPI. 

Hopefully I have done something wrong here but I can't seem to figure out what it is.

**Comment by vchuravy** [comment]
Two questions:

1. Have you actually ensured that you get launched on three different nodes and not just the same node three times?
2. Is MPI.jl correctly setup to use the same MPI library as `mpiexec` 

Add a `@show noderank(MPI.COMM_RANK)` and what does  `MPI.identify_implementation()` yield?

**Comment by sash-a** [comment]
1. Definitely am on three nodes here's the output of the pbs nodefile:

```
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0451.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0483.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
cnode0502.cm.cluster
```

2. I'm not sure how I would check this? I've run the command in the setup guide to use the system MPI.  
`which mpiexec: /apps/chpc/compmech/mpich-3.3-gcc-8.3.0/bin/mpiexec`  

Here's some output with `noderank` and `MPI.identify_implementation()` I see that the implementation is MPICH, but I assume 0.0.0 is an issue?
```
noderank(comm) = 2
noderank(comm) = 0
noderank(comm) = 1
MPI.identify_implementation() = (MPI.MPICH, v"0.0.0")
MPI.identify_implementation() = (MPI.MPICH, v"0.0.0")
[49, 2] end: 1519888704
[1, 0] end: 1530379783
MPI.identify_implementation() = (MPI.MPICH, v"0.0.0")
[25, 1] end: 1575214449
```

**Comment by simonbyrne** [comment]
I think you're just testing the overhead of compilation + threading calls. In the first case (no MPI), the actual work (`sleep(0.1)`) should take 0.9 seconds, and in the second (MPI) case it should be 0.3 seconds. However you're seeing 1.22 & 1.56 seconds. See the usual [Julia performance tips](v), in particular avoiding non-constant globals and putting stuff inside functions. Also would be useful to know what the threading overhead of a complete no-op is.

**Comment by simonbyrne** [comment]
> I see that the implementation is MPICH, but I assume 0.0.0 is an issue?

It shouldn't be, but I'm surprised about that. What is `MPI.MPI_LIBRARY_VERSION_STRING`?

**Comment by sash-a** [comment]
> I think you're just testing the overhead of compilation + threading calls.

You're probably right on this, I've bumped it to `n = Threads.nthreads() * 900 / nnodes(comm)` so I'd expect 90 seconds for the single node version and 30 for the 3 node version, which should outweigh the compilation time. I've also wrapped all the calls in a function:

```
function main()
    MPI.Init()
    comm = MPI.COMM_WORLDdd
    # comm = ThreadComm()

    ts = time_ns()
    n = Threads.nthreads() * 900 / nnodes(comm)

    @qthreads for i in 1:n
        sleep(0.1)
    end
    @show noderank(comm) MPI.identify_implementation() MPI.MPI_LIBRARY_VERSION_STRING
    println("[$(procrank(comm)), $(noderank(comm))] end: $((time_ns() - ts)/1e9)")
end

main()
``` 

MPI.MPI_LIBRARY_VERSION_STRING (looks correct): `MPI.MPI_LIBRARY_VERSION_STRING = "MPICH Version:\t3.3\nMPICH Release date:\tWed Nov 21 11:32:40 CST 2018\nMPICH ABI:\t13:6:1\nMPICH Device:\tch3:nemesis\nMPICH configure:\t--prefix=/apps/chpc/compmech/mpich-3.3-gcc-8.3.0 --with-ibverbs-include=/usr/include/infiniband --with-ibverbs-lib=/usr/lib64 --with-device=ch3:nemesis --with-mxm-include=/apps/chpc/earth/WRF-3.7-gcchwl-mpich/LIBRARIES/mxm/include --with-mxm-lib=/apps/chpc/earth/WRF-3.7-gcchwl-mpich/LIBRARIES/mxm/lib --with-pbs=/opt/pbs --with-hydra-bss=pbs --with-hydra-rmk=pbs\nMPICH CC:\t/apps/chpc/compmech/gcc-8.3.0/bin/gcc -I/apps/chpc/compmech/mpich-3.3-gcc-8.3.0/include   -O2\nMPICH CXX:\t/apps/chpc/compmech/gcc-8.3.0/bin/g++   -O2\nMPICH F77:\t/apps/chpc/compmech/gcc-8.3.0/bin/gfortran   -O2\nMPICH FC:\t/apps/chpc/compmech/gcc-8.3.0/bin/gfortran   -O2\n"`

Timing:  
Single node: 91.503371288
Three nodes: 31.260524602s 

So timings are pretty much exactly as expected, I'm going to have another look at my more complex case that was failing and report back in a bit. (The speedy responses are much appreciated)

**Comment by simonbyrne** [comment]
Thanks. I've opened a fix for the version issue (#526).

I'll close for now, but feel free to continue the discussion, or re-open if you find an issue.

**Comment by sash-a** [comment]
Sorry for the delay, but the cluster I have access to went down last night as I finished typing up my message, so I couldn't do anymore tests, but it looks like I am still running into issues in an only slightly different program. The difference being that I am running `f` instead of `sleep`. I feel it must be an issue with [rand and threads](https://discourse.julialang.org/t/random-number-and-parallel-execution/57024) but I can't I think I've done what is recommended.

MPI (24x3): 13.411660688s
Threads (24): 13.060895732s

So threads and MPI are about the same speed, but I'd expect MPI to be about 3x faster. I don't think I'm testing threading/compilation overhead here since I'm running 24 * 9e6 times, but I can't see why I shouldn't be getting a speedup here? My only thought is that it is something to do with `rand` or `f` is not long enough to benefit from the overhead of starting a new thread? Do you have any suggestions on a better function than `f` that doesn't use randomness?

```
using Random
using Future

using ThreadPools
using Base.Threads: @threads, threadid, nthreads
using MPI: MPI, Comm

struct ThreadComm end  # used for when thread only mode

# convenience methods for mpi/thread mode
noderank(comm::Comm) = MPI.Comm_rank(comm)
noderank(::ThreadComm) = 0
procrank(comm) = (noderank(comm) * Threads.nthreads()) + Threads.threadid()
nnodes(comm::Comm) = MPI.Comm_size(comm)
nnodes(::ThreadComm) = 1

# https://discourse.julialang.org/t/random-number-and-parallel-execution/57024
function parallel_rngs(rng::MersenneTwister, n::Integer)
    step = big(10)^20
    rngs = Vector{MersenneTwister}(undef, n)
    rngs[1] = copy(rng)
    for i = 2:n
        rngs[i] = Future.randjump(rngs[i-1], step)
    end
    return rngs
end

function f(n, rngs)
    @threads for i in 1:n
        rng = rngs[threadid()]
        j = Threads.threadid()
        for i in 1:1000
            j += Threads.threadid() * rand(rng)
        end
    end
end

function main()
    MPI.Init()
    comm = MPI.COMM_WORLD
    #comm = ThreadComm()

    mt = MersenneTwister()
    rngs = parallel_rngs(mt, nthreads())

    repeats = 24 * 9e6  # total number of times to run computation across all nodes
    t = time_ns()
    f(repeats / nnodes(comm), rngs)
    println("[$(procrank(comm)), $(noderank(comm))] end: $((time_ns() - t)/1e9)s")
end

main()
```

**Comment by sash-a** [comment]
my bad was just a bug, using `i` for inner and outer loop
