### ISSUE TITLE
InexactError encountered running test 06

### ISSUE THREAD

**Issue by psanan** [JuliaParallel/MPI.jl#53]
After updating to the latest version of julia, I now encounter the following error when running example 6, related to the check that MPI is initialized. (This occurs fairly early on, and is not affected by number of MPI processes and whether the `MPI` or `TCP` option is used).

The check that raises this error was recently added in this commit:
https://github.com/JuliaLang/julia/commit/68d49865d03a830a5cef50dc919d60cfe39d2bbc 

````
$ aprun -n 1 $JULIA 06-cman-transport.jl MPI
ERROR: LoadError: InexactError()
 in convert at bool.jl:6
 in Initialized at /users/psanan/.julia/v0.4/MPI/src/mpi-base.jl:93
 in init_mpi at /users/psanan/.julia/v0.4/MPI/src/cman.jl:265
 in start at /users/psanan/.julia/v0.4/MPI/src/cman.jl:181
 in include at ./boot.jl:253
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:312
 in _start at ./client.jl:412
while loading /users/psanan/.julia/v0.4/MPI/examples/06-cman-transport.jl, in expression starting on line 16
````

**Comment by eschnett** [comment]
This should be corrected by #78.
