### ISSUE TITLE
Switch to Preferences.jl, remove Pkg.build step

### ISSUE THREAD

**Issue by simonbyrne** [JuliaParallel/MPI.jl#535]
We should be able to now replace Pkg.build and our custom environment variable stuff with the new Preferences.jl. This should also make it easier to provide cluster-specific MPI implementations.

Although discussed in other issues, I don't think we have a concrete issue for this. 

1. Figure out some sort of preferences subpackage (#529)
2. Update Yggdrasil packages to use preferences system (@vchuravy has a draft PR https://github.com/JuliaPackaging/Yggdrasil/pull/4073)
3. Move any remaining code generation steps to [Scratch.jl](https://github.com/JuliaPackaging/Scratch.jl)

**Comment by vchuravy** [comment]
Now on master
