### ISSUE TITLE
Switching system binaries fails due to undefined symbols

### ISSUE THREAD

**Issue by sloede** [JuliaParallel/MPI.jl#581]
Trying to switch system binaries after a different system binary has already been installed will fail due to missing symbols at MPI.jl load time.

On HLRS Hawk:
* Clone this repo and dev its packages:
  ```shell
  git clone git@github.com:JuliaParallel/MPI.jl.git
  export JULIA_DEPOT_PATH=$HOME/.julia-mpijl-master
  julia -e 'using Pkg; Pkg.develop(path="MPI.jl/lib/MPIPreferences"); Pkg.develop(path="MPI.jl")'
  ```
* Load OpenMPI and install as system binary
  ```shell
  module load openmpi
  julia -e 'using MPI; MPI.use_system_binary()'
  ```
  will output something like
  ```shell
  ┌ Info: MPI implementation
  │   libmpi = "libmpi"
  │   version_string = "Open MPI v4.0.5, package: Open MPI hpcoft14@hawk-login01 Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020\0"
  │   impl = "OpenMPI"
  │   version = v"4.0.5"
  └   abi = "OpenMPI"
  ┌ Warning: The underlying MPI implementation has changed. You will need to restart Julia for this change to take effect
  │   libmpi = "libmpi"
  │   abi = "OpenMPI"
  │   mpiexec = "mpiexec"
  └ @ MPIPreferences ~/hackathon/MPI.jl/lib/MPIPreferences/src/MPIPreferences.jl:122
  ```
* Check MPI (works): `mpirun -n 2 julia -e 'using MPI; MPI.Init(); println("I am rank $(MPI.Comm_rank(MPI.COMM_WORLD)) of $(MPI.Comm_size(MPI.COMM_WORLD)) ranks")'`
* Switch to different MPI backend
  ```shell
  module load mpt
  ```
* Try to install different MPI backend in MPI.jl
  ```shell
  julia -e 'using MPI; MPI.use_system_binary()'
  ```
  Error output:
  ```shell
  ERROR: InitError: could not load symbol "ompi_mpi_comm_null":
  /opt/hlrs/non-spack/mpi/mpt/2.23/lib/libmpi.so: undefined symbol: ompi_mpi_comm_null
  Stacktrace:
   [1] __init__()
     @ MPI.Consts ~/hackathon/MPI.jl/src/consts/consts.jl:43
   [2] _include_from_serialized(path::String, depmods::Vector{Any})
     @ Base ./loading.jl:768
   [3] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
     @ Base ./loading.jl:854
   [4] _require(pkg::Base.PkgId)
     @ Base ./loading.jl:1097
   [5] require(uuidkey::Base.PkgId)
     @ Base ./loading.jl:1013
   [6] require(into::Module, mod::Symbol)
     @ Base ./loading.jl:997
  during initialization of module Consts
  ```

In my naive understanding of how this newfangled MPIPreferences/Consts works, it seems like the issue is that the constants are (lazily) loaded at initialization time, thus tripping over the non-existing symbols. Any way to work around this?

**Comment by simonbyrne** [comment]
Yeah, it's a chicken and egg problem: that's why there is the MPIPreferences stub package. Try
```
julia -e 'using MPIPreferences; MPIPreferences.use_system_binary()'
```

**Comment by sloede** [comment]
OK, but for this to work you need to install MPIPreferences.jl explicitly, don't you? In that case, shouldn't we maybe simplify the user interface and *not* export `use_system_binary()` and `use_jll_binary()` from MPI.jl, instead asking users to install MPIPreferences.jl if they want to switch?

That way, the default is still sane and usable for new users (MPI.jl comes with the JLL backend and thus "batteries included"), while for power users there is no confusion as to when you can switch between backends using MPI.jl and when you need to go through MPIPreferences.jl. That is, I propose to
* remove the `export` from https://github.com/JuliaParallel/MPI.jl/blob/d607dc95d9a2aaf668ff7a0405b49b0f61d5b308/src/MPI.jl#L38-L39
* update the docs in https://juliaparallel.org/MPI.jl/latest/configuration/#Using-MPIPreferences.jl to reflect that you need to do a `julia -e 'using Pkg; Pkg.install("MPI")'` before being able to switch backends

**Comment by simonbyrne** [comment]
I'd be in favor of that: can you open a PR?

**Comment by vchuravy** [comment]
Yeah I was thinking that it would simplify the user experience, but of course loading two MPI into the same process spells trouble. We could run the discovery in a sandboxed process?
