### ISSUE TITLE
Should `MPIPreferences.libmpi` be the absolute path of the library?

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/MPI.jl#593]
At the moment `MPIPreferences` uses [`Libdl.find_library`](https://docs.julialang.org/en/v1/stdlib/Libdl/#Base.Libc.Libdl.find_library) to find libmpi https://github.com/JuliaParallel/MPI.jl/blob/af5e08a328c75b7a9cde485e5db83a8aee517b84/lib/MPIPreferences/src/MPIPreferences.jl#L102 but at least for me on Linux this only returns the string `"libmpi"`, or whatever was found in https://github.com/JuliaParallel/MPI.jl/blob/af5e08a328c75b7a9cde485e5db83a8aee517b84/lib/MPIPreferences/src/MPIPreferences.jl#L93  Should it instead use the absolute path, which can be obtained with [`Libdl.dlpath(libmpi)`](https://docs.julialang.org/en/v1/stdlib/Libdl/#Base.Libc.Libdl.dlpath)?  Same for `mpiexec` when it's a string.  I'm thinking of the case where on a cluster there are different MPI modules, you configure `MPI.jl` with a certain module loaded and then accidentally try and run with a different module (and maybe different MPI ABI) loaded.  Having the right module loaded would still be useful, but in most cases you can get away with only using absolute paths.

**Comment by simonbyrne** [comment]
That was somewhat intentional: if you switch between different versions of MPICH then you shouldn't need to recompile.

**Comment by giordano** [comment]
Uhm, OK, I didn't think of that use case, I was more worried about getting into an inconsistent case.

Now that I think of it, I'm actually running the benchmarks over at https://github.com/giordano/julia-on-fugaku on both Fugaku and my laptop, for testing, with this [`LocalPreferences.toml`](https://github.com/giordano/julia-on-fugaku/blob/81190ad47892f4bc4e98fde0d32963497f73d252/benchmarks/mpi-pingpong/LocalPreferences.toml) which works also on my computer because my system MPI incidentally is OpenMPI.  So yeah, this is indeed quite useful :smile:
