### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by kshyatt** [JuliaParallel/MPI.jl#61]
The last tagged version is from more than 6 months ago, when this project didn't even have a `runtests.jl` file. A bunch of functionality has been added since. Should we tag a new version (since I'm using 2FA I can't)?

**Comment by jakebolewski** [comment]
This makes sense now that 0.4 is imminent. Why can't you tag?  If I can surely you can as we are both part of the organization.

**Comment by kshyatt** [comment]
When I try to do it on the CLI git freaks out because I have 2FA turned on for Github and it doesn't want to let me. Then my whole repo goes nuts.

**Comment by jakebolewski** [comment]
Well, preventing you from doing anything is obviously very secure.  I can tag a new version.

**Comment by ViralBShah** [comment]
If it helps, the thing with 2FA is that you have to do the user/password thing twice, and it is not visible the second time or some such thing. This is discussed in an issue too.
