### ISSUE TITLE
Null pointer returned when deriving custom datatypes on OpenMPI

### ISSUE THREAD

**Issue by calebwin** [JuliaParallel/MPI.jl#612]
I'm running into the following problem that seems to affect all `Types.create_*` functions in MPI.jl.
```
julia> MPI.Types.create_vector!(MPI.Datatype(), Int32(3), Int32(2), Int32(5), MPI.Datatype(Int64))
MPI.Datatype(Ptr{Nothing} @0x0000000003d91510)
```
It happens on OpenMPI 4.1.1 implementing MPI 3.1.0 on Amazon Linux 2 but _not_ on MPICH 4.0.1 implementing MPI 1.7.3 on Ubuntu.

**Comment by giordano** [comment]
I'm very confused by the title: where is the null pointer?

**Comment by simonbyrne** [comment]
Did you mean the `Ptr{Nothing}` type? That is just how Julia internally represents pointers to opaque objects (which is how Open MPI represents types, where as MPICH uses integers).

**Comment by calebwin** [comment]
> Did you mean the Ptr{Nothing} type? That is just how Julia internally represents pointers to opaque objects (which is how Open MPI represents types, where as MPICH uses integers).

Oh wow, I had no idea until now. Thanks!

> I'm very confused by the title: where is the null pointer?

So it looks like there is no null pointer. :sweat_smile:  I'm closing the issue because I don't have anything reproducible. It did seem like I wasn't able to successfully derive MPI datatypes for my use-case (calling MPI.Reduce on vectors where the reducing function would operate on the vectors - not corresponding elements of the vectors). I got around that by converting vectors to tuples which works for now.

As a side note: I actually have a working implementation of a variable-sized reduction (https://github.com/JuliaParallel/MPI.jl/issues/531) though it seems to have exorbitant compilation overhead that I would have to investigate. I will try to make a PR when I get a chance.

**Comment by simonbyrne** [comment]
> It did seem like I wasn't able to successfully derive MPI datatypes for my use-case (calling MPI.Reduce on vectors where the reducing function would operate on the vectors - not corresponding elements of the vectors).

I did consider making that an interface, but the standard seems to imply that operators have to work element-wise

> Let u[0], . . ., u[len-1] be the len elements in the communication buffer described by the
arguments invec, len and datatype when the function is invoked; let v[0], . . . , v[len-1] be len
elements in the communication buffer described by the arguments inoutvec, len and datatype
when the function is invoked; let w[0], . . . , w[len-1] be len elements in the communication
buffer described by the arguments inoutvec, len and datatype when the function returns;
then w[i] = u[i]◦v[i], for i=0 , . . . , len-1, where ◦ is the reduce operation that the function
computes.

It might also be possible to make it work somehow using a custom datatype, but that would be even more complicated.
