### ISSUE TITLE
MPI broken on OS X

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#62]
I have just updated MPI, and I now see this error when I say `using MPI`:
```
julia> using MPI
ERROR: LoadError: LoadError: UndefVarError: RTLD_LAZY not defined
 in include at /Users/eschnett/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/eschnett/julia/lib/julia/sys.dylib
 in include at /Users/eschnett/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/eschnett/julia/lib/julia/sys.dylib
 in require at /Users/eschnett/julia/lib/julia/sys.dylib
while loading /Users/eschnett/.julia/v0.4/MPI/src/../deps/src/compile-time.jl, in expression starting on line 1
while loading /Users/eschnett/.julia/v0.4/MPI/src/MPI.jl, in expression starting on line 3
```
Where should this symbol be defined?

**Comment by andreasnoack** [comment]
How recent is you Julia version and have you tried to complete delete the build directory from MPI? At som epoint I had the same error on my Mac, but I don't see it anymore.

**Comment by eschnett** [comment]
My Julia is 0.4 from yesterday. I did remove MPI (as well as the respective cache and lib directories), and installed it anew. I'll try again.

**Comment by eschnett** [comment]
The problem remains, with a fresh Julia build and a fresh MPI checkout.

**Comment by eschnett** [comment]
I notice that `Base` does not export `RTLD_LAZY`. I can correct the error by replacing `RTLD_LAZY` by `Libdl.RTLD_LAZY` in `compile-time.jl`.

**Comment by eschnett** [comment]
I also see warnings such as
```
WARNING: dlopen is deprecated, use Libdl.dlopen instead.
WARNING: dlsym is deprecated, use Libdl.dlsym instead.
```
that point into the same direction.

**Comment by andreasnoack** [comment]
Are you sure you deleted `deps/src`? In my `deps/src/compilte-time.jl` the `Libdl` module is already added to before `dlsym`.

**Comment by eschnett** [comment]
I deleted all of MPI, including the `deps` directory, and checked it out anew.

I'm on MPI version 0.2.6. Which one do you have?

**Comment by eschnett** [comment]
Found the problem -- an unrelated local directory called `MPI`. Everything is fine now.
