### ISSUE TITLE
`MPI.Init` on ACHER2 either segfaults or hangs most of the time on multi-node jobs

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/MPI.jl#623]
On [ARCHER2](https://www.archer2.ac.uk/) (UK Tier-1 system), I'm observing that calling `MPI.Init` with system's Cray MPICH (version string `"MPI VERSION    : CRAY MPICH version 8.1.4.31 (ANL base 3.4a2)\nMPI BUILD INFO : Thu Mar 18 17:07 2021 (git hash 3e74f0c)\n"`) either segfaults or hangs most of the time when running multi-node jobs.  Note: this happens only on `master` of `MPI.jl`, but not v0.19.2, so it'd appear something wrong is going on with `MPI.jl#master`.

I don't have much time to investigate this further at the moment, I'm opening this issue as a reminder to try and look into this at some point.

**Comment by simonbyrne** [comment]
Bisection time!

**Comment by giordano** [comment]
I'm utterly confused: hangs/segfaults happen if I install MPI.jl with `]add MPI#4a87d7402ac3baba5cc97bfd8d5bd4cfbb825525`, but not if I `]dev MPI` and check out the same revision :neutral_face: my attempt to git bisect the issue failed badly because `dev`'ing the package works.  This makes extremely little sense to me.

**Comment by giordano** [comment]
I forgot about that one, thanks for pointing it out.  I'm not sure, `]add MPI` works fine for me, and this installs 0.19.2 which seems to be version used in #616 (at least, they mention the `JULIA_MPI_*` environment variables).  It's only when I do `]add MPI#4a87d7402ac3baba5cc97bfd8d5bd4cfbb825525` (but not `]dev MPI`) that I get the segfaults, or more often hangs.  I know this sounds absurd, I'm also at a loss here.

**Comment by giordano** [comment]
I'm going to close the ticket as I can't reproduce the issue anymore with `]add MPI#4cd71180218a5bb2e88a7c153ef8538dbb7ea74e`.  Sigh.
