### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/MPI.jl#63]
I dont' know if this works

**Comment by kshyatt** [comment]
I tried it on `julia.mit.edu`. The `.ji` builds fine but all the tests fail.

```julia
kshyatt@julia:~/.julia/v0.4/MPI/test$ mpirun -np 3 ~/julia/julia test_scatter.jl
ERROR: LoadError: ccall: null function pointer
 in Init at /home/kshyatt/.julia/v0.4/MPI/src/mpi-base.jl:78
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/kshyatt/.julia/v0.4/MPI/test/test_scatter.jl, in expression starting on line 4
ERROR: LoadError: ccall: null function pointer
 in Init at /home/kshyatt/.julia/v0.4/MPI/src/mpi-base.jl:78
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/kshyatt/.julia/v0.4/MPI/test/test_scatter.jl, in expression starting on line 4
ERROR: LoadError: ccall: null function pointer
 in Init at /home/kshyatt/.julia/v0.4/MPI/src/mpi-base.jl:78
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/kshyatt/.julia/v0.4/MPI/test/test_scatter.jl, in expression starting on line 4

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 17301 RUNNING AT julia
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

**Comment by eschnett** [comment]
MPI looks up symbols in the MPI library. This currently happens when the module is loaded, which breaks precompiling. Hence the `null` function pointers.

To fix this, I assume this lookup needs to happen in an `__init__`. This could be combined with another cleanup: Currently, all MPI function names are pre-processed at build time, and files `jlmpi_f2c.h` and `make_f2c.c` are autogenerated. If the name mangling is instead handled by Julia at module loading time, things become much more flexible.

**Comment by kshyatt** [comment]
@eschnett I'm not very informed about how precompilation works, but does your suggestion mean we could take down #59 too?

**Comment by eschnett** [comment]
No. This is about function pointers; how the MPI data types are defined is still difficult to access from `MPI.jl`. Something like `Cxx.jl` is probably the cleanest way for this.

**Comment by stevengj** [comment]
The right thing to do is to not call `dlsym` at all.  Just do `ccall((symbol, libmpiname), ....)`.

**Comment by eschnett** [comment]
I guess the explicit calls to `dlsym` were introduced since the names of the functions are only determined at configure time. However, instead of resolving them via `dlsym`, we could define strings (or symbols), and use these to call the MPI functions.

**Comment by stevengj** [comment]
Yup, since the names are determined in `Pkg.build`, we can just define them as symbols.

**Comment by stevengj** [comment]
Okay, my precompilation PR is passing Travis now...
