### ISSUE TITLE
Add automatic docstrings to functions in `API` module

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/MPI.jl#651]
Now that we have full low-level API, I think it'd be nice to have it in the documentation.  But this would require attaching a docstring (with link to MPICH docs?) to the automatically generated methods, which at the moment don't have a type signature.  No idea how feasible is that with `Clang.jl`.

CC: @t-bltg

**Comment by t-bltg** [comment]
Fair enough, I'll see what I can do (we systematically think about the docs later :laughing:).
