### ISSUE TITLE
Switching to default JLL-provided binary

### ISSUE THREAD

**Issue by sloede** [JuliaParallel/MPI.jl#661]
As far as I can tell, [`MPIPreferences.use_jll_binary`](https://juliaparallel.org/MPI.jl/dev/reference/mpipreferences/#MPIPreferences.use_jll_binary) requires to manually specify the desired JLL binary to use. IIRC, setting `JULIA_MPI_BINARY=""` (to the empty string) automatically selected the default JLL binary. This was convenient if you just wanted to restore MPI.jl to "factory defaults". Would it be possible to bring this back, i.e., a `MPIPreferences.use_jll_binary` method without the `binary` argument that then selects the default depending on the OS?

**Comment by giordano** [comment]
https://github.com/JuliaParallel/MPI.jl/blob/8d36c1f8bec08bb481f0aae104f2682c4a8ea575/lib/MPIPreferences/src/MPIPreferences.jl#L65
It's already the case?  Also, the docstring says

> - `"MicrosoftMPI_jll"` (Only option and default on Winddows)
> - `"MPICH_jll"` (Default on all other platform)
>

**Comment by sloede** [comment]
Ah, then I got confused by the docstring. Can we maybe change
https://github.com/JuliaParallel/MPI.jl/blob/8d36c1f8bec08bb481f0aae104f2682c4a8ea575/lib/MPIPreferences/src/MPIPreferences.jl#L53
to something like
```julia
"""
    MPIPreferences.use_jll_binary([binary]; export_prefs=false, force=true)
...
"""
```
?

**Comment by giordano** [comment]
Sounds good with me
