### ISSUE TITLE
How to correctly set up MPI.jl (v0.20.4) on slurm cluster

### ISSUE THREAD

**Issue by deltaeecs** [JuliaParallel/MPI.jl#683]
I run 
```julia
MPIPreferences.use_system_binary(; library_names = ["libpmi", "libmpi2", "libslurm"], mpiexec = "srun", abi = "MPICH")
```
on the cluster to set up the MPI.jl. However, when I run 
```julia
using MPI
```
after restarted the REPL, I got the following error
```julia
julia> using MPI
[ Info: Precompiling MPI [da04e1cc-30fd-572f-bb4f-1f8673147195]
ERROR: LoadError: could not load symbol "MPI_Get_library_version":
/public/home/cfdhpc/pkuxia/software/julia/julia-1.8.3/bin/julia: undefined symbol: MPI_Get_library_version
Stacktrace:
 [1] MPI_Get_library_version
   @ ~/.julia/packages/MPI/tJjHF/src/api/generated_api.jl:1953 [inlined]
 [2] Get_library_version()
   @ MPI ~/.julia/packages/MPI/tJjHF/src/implementations.jl:16
 [3] top-level scope
   @ ~/.julia/packages/MPI/tJjHF/src/implementations.jl:22
 [4] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [5] include(x::String)
   @ MPI ~/.julia/packages/MPI/tJjHF/src/MPI.jl:1
 [6] top-level scope
   @ ~/.julia/packages/MPI/tJjHF/src/MPI.jl:62
 [7] include
   @ ./Base.jl:419 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [9] top-level scope
   @ stdin:1
in expression starting at /public/home/cfdhpc/pkuxia/.julia/packages/MPI/tJjHF/src/implementations.jl:22
in expression starting at /public/home/cfdhpc/pkuxia/.julia/packages/MPI/tJjHF/src/MPI.jl:1
```

Is there something wrong with my setting up steps? I'll be appreciated if any one can help me.

**Comment by giordano** [comment]
Can you please provide more information about your system?  What's the output of
```julia
MPIPreferences.use_system_binary(; library_names = ["libpmi", "libmpi2", "libslurm"], mpiexec = "srun", abi = "MPICH")
```
when you run that command?  Additionally, are you loading some modules to bring your MPI library into scope?  If so, which?  Do you know what MPI library (name and version) you're trying to use?

**Comment by vchuravy** [comment]
I don't think `libslurm` contains a valid MPI library, you can drop in `srun` as `mpiexec` but `libslurm` is not `libmpi`

**Comment by deltaeecs** [comment]
> Can you please provide more information about your system? What's the output of
> 
> ```julia
> MPIPreferences.use_system_binary(; library_names = ["libpmi", "libmpi2", "libslurm"], mpiexec = "srun", abi = "MPICH")
> ```
> 
> when you run that command? Additionally, are you loading some modules to bring your MPI library into scope? If so, which? Do you know what MPI library (name and version) you're trying to use?

Hi, giordano, the output is
```julia
MPIPreferences.use_system_binary(; library_names = ["libpmi", "libmpi2", "libslurm"], mpiexec = "srun", abi = "MPICH")
┌ Info: MPIPreferences changed
│   binary = "system"
│   libmpi = "libpmi"
│   abi = "MPICH"
└   mpiexec = "srun"
```

I'm new to the slurm cluster, the expample code gaven in the home dictionary show that to run a mpi program on cluster, one should run `srun --mpi=pmi2`, which is the lib provided by slurm.

Shall I install other mpi library like MPICH to initialize MPI.jl?

**Comment by deltaeecs** [comment]
> Shall I install other mpi library like MPICH to initialize MPI.jl?

Hi vchuravy, shall I intsall other MPI library and run something like this?
```julia
MPIPreferences.use_system_binary(;library_names = ["libmpich", "libmpi"], mpiexec = "srun")
```
In this way, will lack of `libpmi` influence the communication efficency between nodes?

**Comment by deltaeecs** [comment]
> Did you mean to write `libpmi` in your initial command? Or did you mean `libmpi`. Both of them are libraries, but only the latter is relevant here.

I think I should first figure out the difference between `libpmi` and `libmpi`, thanks!

**Comment by giordano** [comment]
What if you don't pass `library_names` at all and rely on default values?
