### ISSUE TITLE
`Char` datatype isn't handled correctly

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/MPI.jl#688]
I'm not sure the `Char` datatype is handled correctly throughout `MPI.jl`.  For example, with `MPICH_jll` I get this on my machine:
```julia
julia> using MPI

julia> MPI.Init()
MPI.ThreadLevel(2)

julia> MPI.Datatype(Char)
MPI.Datatype(Char): 

julia> MPI.get_name(MPI.Datatype(Char))
""

julia> MPI.get_name.(MPI.Datatype.(Base.uniontypes(MPI.MPIDatatype)))
13-element Vector{String}:
 "MPI_C_COMPLEX"
 "MPI_C_DOUBLE_COMPLEX"
 ""
 "MPI_FLOAT"
 "MPI_DOUBLE"
 "MPI_INT16_T"
 "MPI_INT32_T"
 "MPI_INT64_T"
 "MPI_INT8_T"
 "MPI_UINT16_T"
 "MPI_UINT32_T"
 "MPI_UINT64_T"
 "MPI_UINT8_T"
```
`Char` is the only element of `MPI.MPIDatatype` (BTW, this constant is only ever used in the tests, so I'm not sure why it's defined in `src/`)
https://github.com/JuliaParallel/MPI.jl/blob/a179cf876a52876d297b7e635881dbc7a2f3a81c/src/buffers.jl#L5-L8
for which [`get_name`](https://github.com/JuliaParallel/MPI.jl/blob/a179cf876a52876d297b7e635881dbc7a2f3a81c/src/datatypes.jl#L59-L65) returns an empty string, and my understanding is that this is kinda an indication MPI doesn't really know about this type.  @eschnett [suggested](https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341860002) `Char` should behave closer to `UInt32`, however I'm missing where/how this should be fixed.

`MPI.jl` behaving weirdly with `Char` is probably the cause of most issues in #684 but not all of them, so I opened this issue to track specifically the problems with `Char`.

**Comment by giordano** [comment]
From https://github.com/JuliaParallel/MPI.jl/pull/689#issue-1492688679

> An easy fix to #688.

I don't think #689 was a real fix for this issue, we're just skipping the `Char` tests, but the `Char` datatype is still used incorrectly and https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341698748 still segfaults for me with
```console
$ srun -n 2 julia --project test.jl 

[49022] signal (11.1): Segmentation fault
in expression starting at none:0

[49023] signal (11.1): Segmentation fault
in expression starting at none:0
MPIR_Call_attr_delete at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
MPIR_Attr_delete_list at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
Allocations: 634797 (Pool: 634278; Big: 519); GC: 1
MPIR_Call_attr_delete at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
MPIR_Attr_delete_list at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
Allocations: 634795 (Pool: 634276; Big: 519); GC: 1
srun: error: fj001: tasks 0-1: Segmentation fault (core dumped)
```
while https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341883353 always works.  Where can we tell MPI to treat `Char` like `UInt32`?

**Comment by simonbyrne** [comment]
Curious: can you try running my C code: https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1347325356?

**Comment by simonbyrne** [comment]
Actually it looks like the error might be in the attribute handling. can you try commenting out this line:
https://github.com/JuliaParallel/MPI.jl/blob/7da078cf179a4d39e555713acaa74c84dbbf6729/src/datatypes.jl#L146

**Comment by giordano** [comment]
> Actually it looks like the error might be in the attribute handling. can you try commenting out this line:
https://github.com/JuliaParallel/MPI.jl/blob/7da078cf179a4d39e555713acaa74c84dbbf6729/src/datatypes.jl#L146

That seems to work!
```console
[mosgiordano@fj001 tmp]$ srun -n 8 julia --project=mvapich mvapich/test.jl 
(rank, C) = (1, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (2, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (3, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (5, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (4, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (0, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (7, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (6, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
```

**Comment by simonbyrne** [comment]
Thanks! based on the error message, it looks like it is the attribute delete function that is causing problems (presumably this is being called in `MPI_Finalize`?)

We define it to be the default one (`MPI_TYPE_NULL_DELETE_FN`)
https://github.com/JuliaParallel/MPI.jl/blob/e28a639c9ff0322d260c7603940cd147f7bacfac/src/datatypes.jl#L40
which in the MPICH header is just the null pointer
https://github.com/JuliaParallel/MPI.jl/blob/47ec5ccdf1faad001a57dd0c124bae85c93318cd/src/api/mpich.jl#L335

Is it different in the MVAPICH header?

**Comment by giordano** [comment]
> Thanks! based on the error message, it looks like it is the attribute delete function that is causing problems (presumably this is being called in MPI_Finalize?)

Yeah, lots of the MVAPICH segfaults in #684 happen on the `MPI_Finalize` line.

> Is it different in the MVAPICH header?

```console
$ echo '#include <mpi.h>' | mpicc -dM -E - | grep MPI_TYPE_NULL_DELETE_FN
#define MPI_TYPE_NULL_DELETE_FN ((MPI_Type_delete_attr_function*)0)
```
seems to be null pointer as well>

**Comment by simonbyrne** [comment]
I wonder if the types are correct. In C the signature is:
```C
int MPI_Type_create_keyval(MPI_Type_copy_attr_function *type_copy_attr_fn,
             MPI_Type_delete_attr_function *type_delete_attr_fn,
             int *type_keyval, void *extra_state)
```
whereas we have:
https://github.com/JuliaParallel/MPI.jl/blob/8d36c1f8bec08bb481f0aae104f2682c4a8ea575/src/api/generated_api.jl#L161-L163

I think the `MPIPtr` should be Ptr{MPI_Type_copy_attr_function}` and `Ptr{MPI_Type_delete_attr_function}`, respectively. We would then have to also remove the `[]` from
https://github.com/JuliaParallel/MPI.jl/blob/e28a639c9ff0322d260c7603940cd147f7bacfac/src/datatypes.jl#L40

**Comment by simonbyrne** [comment]
Huh. I think we must still have the types wrong: the function signature is:
```C
typedef int MPI_Type_delete_attr_function(MPI_Datatype datatype,
             int type_keyval, void *attribute_val, void *extra_state);
```
I always get confused with C function pointers

**Comment by simonbyrne** [comment]
What about simply changing:
```patch
diff --git a/src/api/generated_api.jl b/src/api/generated_api.jl
index 186ac85..eebfec1 100644
--- a/src/api/generated_api.jl
+++ b/src/api/generated_api.jl
@@ -159,7 +159,7 @@ end
 $(_doc_external(:MPI_Type_create_keyval))
 """
 function MPI_Type_create_keyval(type_copy_attr_fn, type_delete_attr_fn, type_keyval, extra_state)
-    @mpichk ccall((:MPI_Type_create_keyval, libmpi), Cint, (MPIPtr, MPIPtr, Ptr{Cint}, MPIPtr), type_copy_attr_fn, type_delete_attr_fn, type_keyval, extra_state)
+    @mpichk ccall((:MPI_Type_create_keyval, libmpi), Cint, (MPI_Type_copy_attr_function, MPI_Type_delete_attr_function, Ptr{Cint}, MPIPtr), type_copy_attr_fn, type_delete_attr_fn, type_keyval, extra_state)
 end
 
 """
```

**Comment by giordano** [comment]
Yes, that works!
```console
[mosgiordano@fj001 mvapich]$ srun -n 2 julia --project test.jl 
(rank, C) = (0, ['\x01', '\x02'])
(rank, C) = (1, ['\x01', '\x02'])
[mosgiordano@fj001 mvapich]$ srun -n 4 julia --project test.jl 
(rank, C) = (1, ['\x01', '\x02', '\x03', '\x04'])
(rank, C) = (2, ['\x01', '\x02', '\x03', '\x04'])
(rank, C) = (3, ['\x01', '\x02', '\x03', '\x04'])
(rank, C) = (0, ['\x01', '\x02', '\x03', '\x04'])
[mosgiordano@fj001 mvapich]$ srun -n 8 julia --project test.jl 
(rank, C) = (4, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (5, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (2, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (3, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (7, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (1, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (0, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
(rank, C) = (6, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b'])
[mosgiordano@fj001 mvapich]$ srun -n 16 julia --project test.jl 
(rank, C) = (13, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (15, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (12, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (14, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (5, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (11, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (2, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (0, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (1, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (3, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (4, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (9, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (10, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (6, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (8, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
(rank, C) = (7, ['\x01', '\x02', '\x03', '\x04', '\x05', '\x06', '\a', '\b', '\t', '\n', '\v', '\f', '\r', '\x0e', '\x0f', '\x10'])
```

I guess that's going to be hard to fix in the autogenerated API because Clang.jl just sees those pointers as `Ptr{Cvoid}`: https://github.com/JuliaParallel/MPI.jl/blob/7da078cf179a4d39e555713acaa74c84dbbf6729/gen/src/MPIgenerator.jl#L68 :confused:

**Comment by simonbyrne** [comment]
@t-bltg any ideas?

**Comment by giordano** [comment]
Actually, `Ptr{Cvoid}` would even be correct:
```julia
julia> MPI.API.MPI_Type_delete_attr_function
Ptr{Nothing}

julia> MPI.API.MPI_Type_copy_attr_function
Ptr{Nothing}
```
So the replacement `"Ptr{Cvoid}" => "MPIPtr"` is too aggressive?

**Comment by giordano** [comment]
@Gnimuc in Clang.jl is there a way to generate the wrappers with `@ccall` instead of `ccall`?  I think we could replace only the types for arguments called `buffer`/`sendbuf`/`recvbuf`/etc and that's much easier with `@ccall`.

**Comment by Gnimuc** [comment]
You could add the following setting in toml:
[codegen]
use_ccall_macro = true

令和4年12月16日(金) 9:46 Mosè Giordano ***@***.***>:

**Comment by simonbyrne** [comment]
Yeah, MPIPtr should only be used for actual buffers (it's there for CuArray support)

**Comment by Gnimuc** [comment]
Here is an example for rewriting the generated expressions before printing.

build!(ctx, BUILDSTAGE_NO_PRINTING)

function rewrite!(dag::ExprDAG)
    replace!(get_nodes(dag)) do node
        cur_name = Clang.name(node.cursor)
        there are other utility functions in Clang or Clang.Generators for filtering the target node.
    
        return node
    end
end

rewrite!(ctx.dag)

build!(ctx, BUILDSTAGE_PRINTING_ONLY)

**Comment by t-bltg** [comment]
Hum that's a weird one.

> We want to replace only some Ptr{Cvoid}, depending on the name of the argument (with the hope the name is always meaningful...)

iiuc all the arguments matching `MPI_Type_\w+\s*\*` ?

**Comment by Gnimuc** [comment]
Perhaps we can use [the following two config entries](https://github.com/JuliaInterop/Clang.jl/blob/e40caee81da9c2ff252468e425096e3f594cbabd/gen/generator.toml#L153-L157) to avoid generating `Ptr{Cvoid}` in `ccall` expressions:

```

[codegen]
# if true, opaque pointers in function arguments will be translated to `Ptr{Cvoid}`.
opaque_func_arg_as_PtrCvoid = false

# if true, opaque types are translated to `mutable struct` instead of `Cvoid`.
opaque_as_mutable_struct = true
```

**Comment by t-bltg** [comment]
I've tried that, unfortunately no success.
