### ISSUE TITLE
Take function prototypes seriously

### ISSUE THREAD

**Issue by Gnimuc** [JuliaParallel/MPI.jl#694]
`MPI_Type_delete_attr_function` is a function prototype, not a function pointer. 

The type of `type_delete_attr_fn` is a function pointer(`MPI_Type_delete_attr_function *`).  `MPI_Type_delete_attr_function` is a function prototype used for declaring this pointer.
```c
int MPI_Type_create_keyval(MPI_Type_copy_attr_function *type_copy_attr_fn,
             MPI_Type_delete_attr_function *type_delete_attr_fn,
             int *type_keyval, void *extra_state)
```

This is the declaration of `MPI_Type_delete_attr_function`:
```c
typedef int MPI_Type_delete_attr_function(MPI_Datatype datatype,
             int type_keyval, void *attribute_val, void *extra_state);
```
which is actually a function prototype and is generally used as a shortcut for declaring pointers.

A function pointer should be declared like this:
```c
typedef int (MPI_Type_delete_attr_function*)(MPI_Datatype datatype,
             int type_keyval, void *attribute_val, void *extra_state);
```

So, the fix in #688 is not right. The root cause is that [these "pointers"](https://github.com/JuliaParallel/MPI.jl/blob/4b9b05f482fb24eab1db2f32352626004b9ebb1c/src/api/mpich.jl#L46-L66) should not be defined as pointers(`Ptr{Cvoid}`).

**Comment by giordano** [comment]
Given the deluge of weird and inconsistent segfaults I'm still getting (see https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1357431382 and following), I'm somewhat glad #693 wasn't enough :grin:

**Comment by t-bltg** [comment]
@Gnimuc, you can add the following test to this PR:

```diff
diff --git a/test/test_errorhandler.jl b/test/test_errorhandler.jl
index 8bb8fe9e..ba9b8958 100644
--- a/test/test_errorhandler.jl
+++ b/test/test_errorhandler.jl
@@ -8,3 +8,27 @@ MPI.Init()
 MPI.set_errorhandler!(MPI.COMM_SELF, MPI.ERRORS_ARE_FATAL)
 @test MPI.get_errorhandler(MPI.COMM_SELF) == MPI.ERRORS_ARE_FATAL

+# the following is testing function pointers, and is adapted from
+# mpi.deino.net/mpi_functions/MPI_Comm_call_errhandler.html
+
+DUMMY_ERR = MPI.API.MPI_ERR_OTHER[]
+DUMMY_COMM = MPI.API.MPI_COMM_WORLD[]
+
+function error_handler(comm_ptr::Ptr, err_ptr::Ptr)
+    comm = unsafe_load(comm_ptr)
+    err = unsafe_load(err_ptr)
+    @test comm == DUMMY_COMM
+    @test err == DUMMY_ERR
+    nothing
+end
+
+error_handler_c = @cfunction(error_handler, Cvoid, (Ptr{MPI.MPI_Comm}, Ptr{Cint}))
+
+comm = MPI.Comm(DUMMY_COMM)
+errh = MPI.get_errorhandler(comm)
+
+MPI.API.MPI_Comm_create_errhandler(error_handler_c, errh)
+MPI.set_errorhandler!(comm, errh)
+MPI.API.MPI_Comm_call_errhandler(comm, DUMMY_ERR)
+
+MPI.Finalize()
```
