### ISSUE TITLE
`MPIPreferences` persist through pre-compilation of Preferences.jl?

### ISSUE THREAD

**Issue by JoshuaLampert** [JuliaParallel/MPI.jl#721]
In [P4est.jl](https://github.com/trixi-framework/P4est.jl) we use MPIPreferences.jl in conjunction with Preferences.jl. It seems like the MPIPreferences set in the LocalPreference.toml persist even if the LocalPreferences.toml is deleted. To recover the behavior start with a Project.toml looking like
```
[deps]
P4est = "7d669430-f675-4ae7-b43e-fab78ec5a902"
```
and empty `~/.julia/compiled/v1.8/Preferences` and `~/.julia/compiled/v1.8/P4est` (and no LocalPreference.toml in active and default project). Then:
```julia
julia> using Pkg; Pkg.activate("."); Pkg.instantiate()
julia> using MPIPreferences
julia> MPIPreferences.use_system_binary()
julia> using Preferences, UUIDs
julia> set_preferences!(
           UUID("7d669430-f675-4ae7-b43e-fab78ec5a902"), # UUID of P4est.jl
           "libp4est" => "/path/to/your/libp4est.so", force = true)
# restart REPL
julia> import Pkg; Pkg.activate(".")
julia> using P4est
# works with the right preferences
# manually delete LocalPreferences.toml and restart REPL
julia> import Pkg; Pkg.activate(".")
julia> using P4est
[ Info: Precompiling P4est [7d669430-f675-4ae7-b43e-fab78ec5a902]
ERROR: LoadError: UndefVarError: libp4est not defined
[...]
```
After deleting the pre-compiled file in `~/.julia/compiled/v1.8/Preferences` it works again, but this shouldn't be necessary, right? The error occurs, when we have MPIPreferences set, but no Preference for "libp4est". So it seems like the MPIPreferences are stored in the pre-compiled file. So how do we properly delete the MPIPreferences again?
Maybe this is related to #646?

CC @sloede, @ranocha

**Comment by simonbyrne** [comment]
I don't have libp4est installed, so I can't replicate it, but can you give the full stacktrace? It is helpful to figure out where exactly the error is occurring.



> Maybe this is related to #646?

That is my guess: the last build of P4est_jll is from July 2022, whereas #646 was fixed in Sept 2022.

**Comment by vchuravy** [comment]
cc: @staticfloat 

So Preferences are indeed cached in the precompilation files. But we check that the hash of the set preferences matches the once we compiled for.

**Comment by JoshuaLampert** [comment]
Alright, you don't really need the libp4est.so, actually. Just set the preference of `libp4est` to some value. This won't be the error after deleting the LocalPreferences.toml and `using P4est`. The full stacktrace is
```
ERROR: LoadError: UndefVarError: libp4est not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/P4est/tZ48i/src/LibP4est.jl:16
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [4] include(x::String)
   @ P4est ~/.julia/packages/P4est/tZ48i/src/P4est.jl:1
 [5] top-level scope
   @ ~/.julia/packages/P4est/tZ48i/src/P4est.jl:14
 [6] include
   @ ./Base.jl:419 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [8] top-level scope
   @ stdin:1
in expression starting at ~/.julia/packages/P4est/tZ48i/src/LibP4est.jl:1
in expression starting at ~/.julia/packages/P4est/tZ48i/src/P4est.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile P4est [7d669430-f675-4ae7-b43e-fab78ec5a902] to ~/.julia/compiled/v1.8/P4est/jl_ztlntb.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1705
 [3] compilecache
   @ ./loading.jl:1649 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
```

So, did I understand it correctly that you suggest adding `Dependency(PackageSpec(name="MPIPreferences", uuid="3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"); compat="0.1", top_level=true),`
[here](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/P4est/build_tarballs.jl#L99)?

**Comment by vchuravy** [comment]
Yes that should fix this.

**Comment by JoshuaLampert** [comment]
Ok, thanks!

**Comment by vchuravy** [comment]
```
julia> using MPIPreferences
[ Info: Precompiling MPIPreferences [3da0fdf6-3ccc-4f1b-acd9-58baa6c99267]

julia> MPIPreferences.binary
"MPICH_jll"

julia> using P4est_jll

julia> P4est_jll.host_platform
Linux x86_64 {cxxstring_abi=cxx11, julia_version=1.8.5, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30, mpi=openmpi}
```

Let's see if https://github.com/JuliaPackaging/Yggdrasil/pull/6417 suffices.

https://github.com/JuliaBinaryWrappers/P4est_jll.jl/blob/2daa63643724498a4da87430f627c30d51c0b455/src/P4est_jll.jl#L6 is missing a `using MPIPreferences`

**Comment by JoshuaLampert** [comment]
Yes, I can confirm that it works now! Thanks a lot @vchuravy!
