### ISSUE TITLE
Different MPIPreferences Configurations for Separate Julia Environments

### ISSUE THREAD

**Issue by hammy4815** [JuliaParallel/MPI.jl#731]
Hi,

I am using MPI on a Linux cluster and want to have different MPI configurations for different Julia environments. One environment is used for debugging interactively and accesses the Julia binary for MPI (MPICH_jll). On the other, where I actually run remotely on the cluster for a full job, I have a separate Julia environment configured for the system binary (openmpi-4.1.3). 

However, when I switch between Julia environments, MPI fails to load and tells me 

```Julia
ERROR: InitError: MPI library has changed, please re-run `Pkg.build("MPI")`.
```

I can build either version and they both run fine, but I do not want to rebuild MPI every time I activate the other Julia environment, as this adds a lot of overhead. It was my understanding that the MPIPreferences was setup on an environment level, so I'm confused why it's telling me to rebuild after switching between the two. 

The problem is not related to whether I am running remotely on the cluster, interactively, or on the login node of my machine. This problem happens on any access point when I switch Julia environments. 

Any help would be appreciated here. Thanks!
Ian

**Comment by giordano** [comment]
What version of `MPI.jl` are you using?  The reference to `Pkg.build` makes me think you're using 0.19-, but latest series 0.20 doesn't use that mechanism anymore.

**Comment by hammy4815** [comment]
I was on 0.19.2. One of my dependencies that I can omit for now required the downgrade for MPI, but I think I will try to get the dependency to upgrade their MPI version needed. I just tested on MPI 0.20.9 without my dependency and that seems to fix my problem. Thank you!
