### ISSUE TITLE
MPIPreferences.use_system_binary() not finding homebrew installation of open-mpi

### ISSUE THREAD

**Issue by cadaverous-lives** [JuliaParallel/MPI.jl#733]
I have installed open-mpi using homebrew on a MacBook Air M2, and I get this error when I try to configure MPI.jl:
```
julia> MPIPreferences.use_system_binary()
ERROR: MPI library could not be found with the following name(s):
    ["libmpi", "libmpi_ibm", "msmpi", "libmpich", "libmpi_cray", "libmpitrampoline"]
If you want to try different name(s) for the MPI library, use
    MPIPreferences.use_system_binary(; library_names=[...])
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] use_system_binary(; library_names::Vector{String}, mpiexec::String, abi::Nothing, export_prefs::Bool, force::Bool)
   @ MPIPreferences ~/.julia/packages/MPIPreferences/cvCac/src/MPIPreferences.jl:153
 [3] use_system_binary()
   @ MPIPreferences ~/.julia/packages/MPIPreferences/cvCac/src/MPIPreferences.jl:140
 [4] top-level scope
   @ REPL[16]:1
```

I also tried to specify the install location using `MPIPreferences.use_system_binary(; library_names=["/opt/homebrew/Cellar/open-mpi/4.1.5/bin"])` and I have tried various variations on the path, such as "/opt/homebrew/Cellar/open-mpi" and "/opt/homebrew/Cellar/open-mpi/4.1.5", but I always get the same error.

Is there something obvious I am missing, or is something going wrong with detecting my installation of open-mpi? I have confirmed that open-mpi is installed correctly and working.

**Comment by giordano** [comment]
> I also tried to specify the install location using `MPIPreferences.use_system_binary(; library_names=["/opt/homebrew/Cellar/open-mpi/4.1.5/bin"])`

`library_names` is a collection of either library names that can be found automatically by the dynamic loader, or full absolute paths of libraries. A directory path would do no good.

**Comment by cadaverous-lives** [comment]
@giordano What would be the absolute path to the library then?

**Comment by giordano** [comment]
I don't know, the path of the MPI library in your system. Maybe something like `/opt/homebrew/Cellar/open-mpi/4.1.5/lib/libmpi.dylib`? I'm just guessing, you'll have to find out yourself, I don't have access to your machine.

**Comment by cadaverous-lives** [comment]
I was able to get it to work, but I'm wondering what went wrong. I guess libmpi is somehow not in `DL_LOAD_PATH` or the system libraries, but I can't imagine how that could be the case...

**Comment by cadaverous-lives** [comment]
@giordano Thanks for your help!

**Comment by giordano** [comment]
> I guess libmpi is somehow not in `DL_LOAD_PATH` or the system libraries, but I can't imagine how that could be the case... 

That's not very surprising, I wouldn't expect homebrew-specific directories to be in the dynamic loader default search paths, so that you have to pass the absolute path of the library.

> I was able to get it to work

Then I'm closing this ticket.
