### ISSUE TITLE
set_attr! fails when using initialized system-provided MPI 

### ISSUE THREAD

**Issue by bgeihe** [JuliaParallel/MPI.jl#746]
Me and @sloede are working on [`libtrixi`](https://github.com/trixi-framework/libtrixi/), which is a C / Fortran interface to the Julia-based flow solver [`Trixi.jl`](https://github.com/trixi-framework/Trixi.jl), which internally uses `MPI.jl`. In our typical user stories, an external application will have MPI already initialized when invoking `libtrixi`. We therefore followed the instructions for [Using a system-provided MPI backend](https://juliaparallel.org/MPI.jl/stable/configuration/#using_system_mpi).

Now we ran into the following error:
```
fatal: error thrown and no exception handler available.
MPI.MPIError(code=16)
MPI_Type_set_attr at ~/libtrixi-julia/dev/MPI/src/api/generated_api.jl:198 [inlined]
set_attr! at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:46 [inlined]
init at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:163
#65 at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:168
get! at ./iddict.jl:178 [inlined]
Datatype at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:156 [inlined]
create! at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:475
unknown function (ip: 0x7eff828f85ee)
unknown function (ip: 0x7eff828e7ecd)
unknown function (ip: 0x7eff828e7e9c)
init at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:160
#65 at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:168
get! at ./iddict.jl:178 [inlined]
Datatype at ~/libtrixi-julia/dev/MPI/src/datatypes.jl:156 [inlined]
RBuffer at ~/libtrixi-julia/dev/MPI/src/buffers.jl:344 [inlined]
Reduce! at ~/libtrixi-julia/dev/MPI/src/collective.jl:592
Reduce! at ~/libtrixi-julia/dev/MPI/src/collective.jl:598
```
`Reduce` is called by `Trixi.jl` here.

Going through the code we realized that 
```
JULIA_TYPE_PTR_ATTR[] = create_keyval(Datatype)
```
is not called when MPI had already been initialized, leading to the error in `MPI_Type_set_attr`. 

We can fix this by running:
```
using MPI
if MPI.Initialized() && MPI.JULIA_TYPE_PTR_ATTR[]==0
    MPI.run_init_hooks()
end
```
Is there any, more natural way to get this right?

**Comment by sloede** [comment]
If there is no canonical approach, maybe a way forward could be to collect all the post-init actions relevant for when MPI was already initialized externally into a single function, and to provide a query function to know when to run them?

I could imagine something like the following in MPI.jl (names, as usual, tbd.):
```julia
const _is_initialized_internal = Ref(false)

function initialize_internal(errors_return=true)
    run_init_hooks()
    if errors_return
        set_default_error_handler_return()
    end
    _warn_if_wrong_mpi()
    _is_initialized_internal[] = true
end

is_initialized_internal() = _is_initialized_internal[]
```
And then replace these lines
https://github.com/JuliaParallel/MPI.jl/blob/2a2bd68a6dc53660108bbc16690e4972de6318d5/src/environment.jl#L145-L149
by a call to `init_internal()`

**Comment by simonbyrne** [comment]
How about https://github.com/JuliaParallel/MPI.jl/pull/747?
