### ISSUE TITLE
MPI.Send cannot work with derived datatypes.

### ISSUE THREAD

**Issue by xwuupb** [JuliaParallel/MPI.jl#776]
For example, the MPI C code shown in https://rookiehpc.org/mpi/docs/mpi_type_vector/index.html cannot be written in Julia with MPI.jl. To be specific, I cannot find a straightforward way to re-write the following C code in Julia, if `buffer[3][3]` is translated as `buffer = Matrix{Int32}(undef, (3, 3))` etc, then no way to use `MPI.Send` in MPI.jl.

```
int buffer[3][3] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 }; // L69 in the above link
MPI_Send(&buffer[0][1], 1, column_type, RECEIVER, 0, MPI_COMM_WORLD); // L72 in the above link
```

**Comment by simonbyrne** [comment]
You should be able to just do
```julia
buffer = reshape(Int32.(0:8), 3,3)
MPI.Send(view(buffer, 2, :), MPI.COMM_WORLD; dest=RECEIVER, tag=0)
```
