### ISSUE TITLE
`mpiexec()` do syntax recommended in docs but deprecated after julia 1.6

### ISSUE THREAD

**Issue by mmesiti** [JuliaParallel/MPI.jl#786]
https://github.com/JuliaParallel/MPI.jl/blob/master/docs/src/usage.md suggests using 
```
mpiexec() do exe  # MPI wrapper
        run(`$exe -n $n $(Base.julia_cmd()) [...]/01-hello.jl`)
        # alternatively:
        # p = run(ignorestatus(`...`))
        # @test success(p)
    end
```
but this causes a deprecation warning (at least in Julia 1.9.3). The inline documentation says that 
```
run(`$(mpiexec()) $arguments`)
```
is threadsafe and should be preferred.

**Comment by simonbyrne** [comment]
Would you mind opening a pull request?
