### ISSUE TITLE
OOM when running embarrassingly parallel tasks

### ISSUE THREAD

**Issue by turquoisedragon2926** [JuliaParallel/MPI.jl#822]
Hello,

Not sure if this is the right place, but I am running into a issue where we observe that we run out of memory on embarrassingly parallel tasks when the memory per task is constant.

More details are here: https://discourse.julialang.org/t/mpi-jl-zygote-oom-on-embarrassingly-parallel-tasks/110622

Thank you for any help

**Comment by simonbyrne** [comment]
I replied on discourse
