### ISSUE TITLE
MPI.jl fails to find homebrew MPI in macos Sonoma runner

### ISSUE THREAD

**Issue by miguelbiron** [JuliaParallel/MPI.jl#828]
Hi folks -- as the title says, we're getting the following error in our CI workflow 

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/8849574516/job/24301884110#step:7:1236

The same happens for openmpi. Not sure if this is an issue on your end or upstream (julia's Libdl).

**Comment by simonbyrne** [comment]
Why not just use the default MPI?

**Comment by miguelbiron** [comment]
Because at some point we did just that, and we realized that many of our users were finding issues that were not being picked up by our CI tests.

**Comment by miguelbiron** [comment]
BTW we basically copied the workflow from you, so we expect that if you rerun your CI you should see the same issues (your last run was 3 days ago and [used the old runners](https://github.com/JuliaParallel/MPI.jl/actions/runs/8807615431/job/24175073871#step:1:4)).

**Comment by giordano** [comment]
Is this because macos-latest now is aarch64-darwin?

**Comment by sloede** [comment]
> Is this because macos-latest now is aarch64-darwin?

I don't know if that's the cause, but yes, they are arm now

**Comment by giordano** [comment]
Would setting macos-13 instead of macos-latest help?

**Comment by sloede** [comment]
That or macos-12 worked for us (on a similar issue, but unrelated to MPI.jl)

**Comment by miguelbiron** [comment]
Testing this right now https://github.com/Julia-Tempering/Pigeons.jl/pull/230

**Comment by giordano** [comment]
We probably still want to understand what's happening, but currently I personally don't have the time to do that, but at least using an older macos image should help with getting a working environment.

**Comment by miguelbiron** [comment]
Ok confirmed that using macos-12 [still works](https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/8851596941/job/24308493240?pr=230#step:7:1236). Per @giordano I'll leave the issue open until a more permanent solution arises.

**Comment by simonbyrne** [comment]
It's failing here as well:
https://github.com/JuliaParallel/MPI.jl/actions/runs/8807615431/job/24305646282

I don't really have the time to look into it at the moment though.

**Comment by giordano** [comment]
> Ah, I think I understand now: up to the `macos-13` image, the `brew` commands used to install packages in `/usr/local` (which is probably a default search path for the dynamic loader), but in `macos-14` they're now installed under `/opt/homebrew`.  I don't know whether this is a change in Homebrew, or macOS, or whatever, but the net result is that `libmpi` isn't anymore in a default search path for the dynamic loader, and so we have to do something #831 to reliably make loading libmpi.  An alternative could be to tell Homebrew to install the packages again in `/usr/local`, but I think setting `DYLD_FALLBACK_LIBRARY_PATH` is slightly more general: we don't have to change the installation directory.

_Originally posted by @giordano in https://github.com/JuliaParallel/MPI.jl/issues/829#issuecomment-2083215272_

**Comment by miguelbiron** [comment]
Thanks for fixing this! I'll borrow your solution for our own MPI tests.

**Comment by miguelbiron** [comment]
Ah thanks yes I just saw that. Will switch to that approach once it is merged
