### ISSUE TITLE
Cannot return user specified exit status with `exit()` when using `mpiexecjl`

### ISSUE THREAD

**Issue by cohensbw** [JuliaParallel/MPI.jl#833]
If the command
```
mpiexecjl -n 2 julia -e "using MPI; MPI.Init(); exit(100)"
```
is run, the reported exit status returned by
```
echo $?
```
will always return `1` regardless of the argument of `exit()`.

**Comment by vchuravy** [comment]
`run` doesn't propagate the exit code. You need `success` or manually capture and propagate it
