### ISSUE TITLE
A segmentation fault occurs when my array is large.

### ISSUE THREAD

**Issue by crazyfireji** [JuliaParallel/MPI.jl#870]
As I mensioned in title,  here is my code, it works when nx_g<=10000, but can't works over it.  Error info: [42194] signal (11.1): Segmentation fault. My compute mem morethan 700G
```julia
function get_Axy_MPI(nx_g, nx0, rank, nprocs, k)
	u_local = zeros(nx0, nx_g)

	if rank == 0
	
		A = zeros(nx_g, nx_g)#calculate_Axy(k) #get_A()#zeros(nx_g, nx_g)

		for sendrank in 0:nprocs-1
		# 计算每个进程的起始行和结束行
			if sendrank == 0
				ilo = 1
				ihi = rows_per_process[1]
				# @show sendrank, ilo,ihi
			else
				ilo = sum(rows_per_process[1:sendrank]) + 1
				ihi = ilo + rows_per_process[sendrank+1] - 1
				@show sendrank, ilo,ihi
			end
			
			#data_on_root = A[ilo:ihi, :]
			sendtag = sendrank + 1000
			MPI.Isend(A[ilo:ihi, :], sendrank, sendtag, comm)
			
			@show ilo, ihi
			
		end

	end

	recievetag = rank + 1000

	MPI.Irecv!(u_local, root, recievetag, comm)
	
	if rank ==0 println("Done！！！")end
	
	MPI.Barrier(comm)
	
	return u_local
	
end
```
![image](https://github.com/user-attachments/assets/c51a4d1a-35bc-4e68-bef2-f5f9863617e8)
![image](https://github.com/user-attachments/assets/df3d79ac-c127-4a6b-a0bb-27e0d418bc77)

**Comment by giordano** [comment]
Can you please show the output of
```julia
using MPI
MPI.versioninfo()
```
What's the `mpiexec` command you're running? Is it the launcher of the MPI library used by `MPI.jl`?

**Comment by crazyfireji** [comment]
> Can you please show the output of
> 
> ```julia
> using MPI
> MPI.versioninfo()
> ```
> 
> What's the `mpiexec` command you're running? Is it the launcher of the MPI library used by `MPI.jl`?
It's MPI info
![image](https://github.com/user-attachments/assets/fb188b86-6b55-40bf-a3f6-3f59a6892a3d)

run command is : mpirun -n 10 julia PrL_MPI.jl

`using MPI
using JLD2
using FFTW

MPI.Init()
comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)
nprocs = MPI.Comm_size(comm)

include("fun_mpi.jl")

const root = 0
nx_g = 90000#size(xx,1)*j2
Ndims = n

nx0 = rows_per_process[rank+1]
# @show rank, nx0

Axy = get_Axy_MPI(nx_g, nx0, rank, nprocs, k)
`

**Comment by giordano** [comment]
> run command is : mpirun -n 10 julia PrL_MPI.jl

That doesn't really answer my question.  What's `mpirun`?  Can you please show the output of the command
```
mpirun --version
```
in the terminal?

Also

* don't share screenshots, they're hard to read and are not searchable, they don't help who wants to help you.  Instead, post output of commands as plain text, quoted as code blocks
* speaking of code blocks, please quote them with ***triple*** backticks
  ````
  ```
  like this
  ```
  ````
